export * from "./angle";
export * from "./table-placement";
export * from "./arc-creation";
export * from "./arc-interaction";
export * from "./anchor-position";
export * from "./arrowhead-trim";
export * from "./block-arrow-geometry";
export * from "./callout-geometry";
export * from "./curve-drawing";
export * from "./graph-label-layout";
export * from "./chart-layout";
export * from "./graph-layout";
export * from "./graph3d-animation";
export { graphVideoAnimationParameters, graphVideoDurationMs, graphParameterAnimationOverridesAt } from "./graph-parameter-animation";
export * from "./graph3d-common-part";
export * from "./graph3d-errors";
export * from "./graph3d-geometry";
export * from "./graph3d-plane";
export * from "./graph3d-presets";
export * from "./graph3d-preview";
export * from "./graph3d-scene";
export * from "./graph3d-solid";
export * from "./graph3d-thumbnail";
export * from "./graph3d-transform";
export * from "./image-crop-geometry";
export * from "./image-insertion";
export * from "./interaction-mode";
export * from "./line-geometry";
export * from "./math";
export * from "./math-expression";
export type * from "./overlay-tool";
export * from "./point-edit";
export * from "./regular-polygon-geometry";
export * from "./resize";
export * from "./resize-frame";
export * from "./selection";
export * from "./shape-arrangement";
export * from "./shape-bounds";
export * from "./shape-label-geometry";
export * from "./shape-style-defaults";
// The one-line caption estimator: the plain-text line box, and the width of a run of characters
// drawn straight into an SVG. `estimateOverlayTextCharUnits` stays internal to the feature.
export { estimateTextWidthEm, TEXT_ASCENT_EM, TEXT_DESCENT_EM } from "./svg-label-metrics";
export * from "./shape-visual-bounds";
export * from "./shape-hit-test";
export * from "./shape-snap-points";
export * from "./shape-transform";
export * from "./snapping";
