import { createCurrentLocaleTranslator, type Translate } from "@/lib/i18n";

export interface TexCommandReference {
  aliases?: readonly string[];
  category: string;
  command: string;
  id: string;
  keywords: readonly string[];
  label: string;
  previewTex: string;
}

interface TexCommandReferenceDescriptor {
  aliases?: readonly string[];
  command: string;
  id: string;
  previewTex: string;
}

const DEFAULT_TEX_TRANSLATE = createCurrentLocaleTranslator("tex");
const KEYWORD_SEPARATOR = "\n";
const LOCALIZED_EXAMPLE_IDS = new Set([
  "fbox",
  "framebox",
  "thickbox",
  "doublebox",
  "ovalbox",
  "shadebox",
  "tcolorbox",
  "itembox",
  "text",
  "sum-with-multiple-conditions",
  "overbrace",
  "underbrace",
]);

const TEX_COMMAND_REFERENCE_DESCRIPTORS: readonly TexCommandReferenceDescriptor[] = [
  { id: "fraction", command: "\\frac{a}{b}", previewTex: "\\frac{a}{b}" },
  { id: "square-root", command: "\\sqrt{x}", previewTex: "\\sqrt{x}" },
  { id: "nth-root", command: "\\sqrt[3]{x}", previewTex: "\\sqrt[3]{x}" },
  { id: "superscript", command: "x^{2}", previewTex: "x^{2}" },
  { id: "subscript", command: "a_{n}", previewTex: "a_{n}" },
  { id: "parentheses", command: "\\left(x+1\\right)", previewTex: "\\left(x+1\\right)" },
  { id: "absolute-value", command: "\\left|x\\right|", previewTex: "\\left|x\\right|" },
  { id: "sine", command: "\\sin x", previewTex: "\\sin x" },
  { id: "cosine", command: "\\cos x", previewTex: "\\cos x" },
  { id: "tangent", command: "\\tan x", previewTex: "\\tan x" },
  { id: "logarithm", command: "\\log_{a} x", previewTex: "\\log_{a} x" },
  { id: "limit", command: "\\lim_{x\\to0} f(x)", previewTex: "\\lim_{x\\to0} f(x)" },
  { id: "summation", command: "\\sum_{k=1}^{n} k", previewTex: "\\sum_{k=1}^{n} k" },
  { id: "product", command: "\\prod_{k=1}^{n} k", previewTex: "\\prod_{k=1}^{n} k" },
  { id: "integral", command: "\\int x\\,dx", previewTex: "\\int x\\,dx" },
  { id: "definite-integral", command: "\\int_{a}^{b} f(x)\\,dx", previewTex: "\\int_{a}^{b} f(x)\\,dx" },
  { id: "alpha", command: "\\alpha", previewTex: "\\alpha", aliases: ["\\al"] },
  { id: "beta", command: "\\beta", previewTex: "\\beta", aliases: ["\\be"] },
  { id: "gamma", command: "\\gamma", previewTex: "\\gamma", aliases: ["\\ga"] },
  { id: "delta", command: "\\delta", previewTex: "\\delta", aliases: ["\\de"] },
  { id: "epsilon", command: "\\epsilon", previewTex: "\\epsilon", aliases: ["\\ep"] },
  { id: "theta", command: "\\theta", previewTex: "\\theta", aliases: ["\\th"] },
  { id: "lambda", command: "\\lambda", previewTex: "\\lambda", aliases: ["\\la"] },
  { id: "phi", command: "\\phi", previewTex: "\\phi", aliases: ["\\ph"] },
  { id: "sigma", command: "\\sigma", previewTex: "\\sigma", aliases: ["\\si"] },
  { id: "omega", command: "\\omega", previewTex: "\\omega", aliases: ["\\om"] },
  { id: "pi", command: "\\pi", previewTex: "\\pi" },
  { id: "less-than-or-equal", command: "\\leqq", previewTex: "a\\leqq b", aliases: ["\\le","\\leq"] },
  { id: "greater-than-or-equal", command: "\\geqq", previewTex: "a\\geqq b", aliases: ["\\ge","\\geq"] },
  { id: "not-equal", command: "\\ne", previewTex: "a\\ne b", aliases: ["\\neq"] },
  { id: "plus-minus", command: "\\pm", previewTex: "x=\\pm1" },
  { id: "multiplication", command: "\\times", previewTex: "a\\times b" },
  { id: "division", command: "\\div", previewTex: "a\\div b" },
  { id: "infinity", command: "\\infty", previewTex: "\\infty", aliases: ["\\infinity"] },
  { id: "to", command: "\\to", previewTex: "x\\to0" },
  { id: "implies", command: "\\Rightarrow", previewTex: "P\\Rightarrow Q" },
  { id: "equivalent", command: "\\Leftrightarrow", previewTex: "P\\Leftrightarrow Q" },
  { id: "degree", command: "^{\\circ}", previewTex: "90^{\\circ}" },
  { id: "element-of", command: "\\in", previewTex: "x\\in A" },
  { id: "not-element-of", command: "\\notin", previewTex: "x\\notin A" },
  { id: "union", command: "\\cup", previewTex: "A\\cup B" },
  { id: "intersection", command: "\\cap", previewTex: "A\\cap B" },
  { id: "vector", command: "\\vec{a}", previewTex: "\\vec{a}" },
  { id: "overline", command: "\\overline{AB}", previewTex: "\\overline{AB}" },
  { id: "hat", command: "\\hat{x}", previewTex: "\\hat{x}" },
  { id: "boxed", command: "\\boxed{x=1}", previewTex: "\\boxed{x=1}" },
  { id: "fbox", command: "\\fbox{重要}", previewTex: "\\boxed{\\text{重要}}" },
  { id: "framebox", command: "\\framebox{重要}", previewTex: "\\boxed{\\text{重要}}" },
  { id: "thickbox", command: "\\thickbox{重要}", previewTex: "\\boxed{\\mathbf{重要}}" },
  { id: "doublebox", command: "\\doublebox{重要}", previewTex: "\\boxed{\\boxed{\\text{重要}}}" },
  { id: "doubleboxed", command: "\\doubleboxed{a}", previewTex: "\\doubleboxed{a}" },
  { id: "thickboxed", command: "\\thickboxed{a}", previewTex: "\\thickboxed{a}" },
  { id: "outerthickdoubleboxed", command: "\\outerthickdoubleboxed{a}", previewTex: "\\outerthickdoubleboxed{a}" },
  { id: "kyoutsuuchoice", command: "\\kyoutsuuchoice{0}", previewTex: "\\kyoutsuuchoice{0}" },
  { id: "ovalbox", command: "\\ovalbox{重要}", previewTex: "\\boxed{\\text{重要}}", aliases: ["\\Ovalbox"] },
  { id: "shadebox", command: "\\shadebox{重要}", previewTex: "\\boxed{\\text{重要}}" },
  { id: "tcolorbox", command: "\\tcolorbox[blue]{重要}", previewTex: "\\boxed{\\text{重要}}", aliases: ["\\tcbox"] },
  { id: "itembox", command: "\\itembox{ポイント}{本文}", previewTex: "\\boxed{\\text{【ポイント】 本文}}" },
  { id: "matrix", command: "\\begin{pmatrix}a&b\\\\c&d\\end{pmatrix}", previewTex: "\\begin{pmatrix}a&b\\\\c&d\\end{pmatrix}" },
  { id: "cases", command: "\\begin{cases}x&x\\geqq0\\\\-x&x<0\\end{cases}", previewTex: "\\begin{cases}x&x\\geqq0\\\\-x&x<0\\end{cases}" },
  { id: "display-fraction", command: "\\dfrac{a}{b}", previewTex: "\\dfrac{a}{b}" },
  { id: "text-fraction", command: "\\tfrac{a}{b}", previewTex: "\\tfrac{a}{b}" },
  { id: "binomial", command: "\\binom{n}{r}", previewTex: "\\binom{n}{r}" },
  { id: "overset", command: "\\overset{!}{=}", previewTex: "\\overset{!}{=}" },
  { id: "underset", command: "\\underset{x}{\\min}", previewTex: "\\underset{x}{\\min}" },
  { id: "display-style", command: "\\displaystyle \\sum_{k=1}^{n} k", previewTex: "\\displaystyle \\sum_{k=1}^{n} k" },
  { id: "text-style", command: "\\textstyle \\sum_{k=1}^{n} k", previewTex: "\\textstyle \\sum_{k=1}^{n} k" },
  { id: "phantom", command: "\\phantom{x}y", previewTex: "\\phantom{x}y" },
  { id: "horizontal-phantom", command: "\\hphantom{x}y", previewTex: "\\hphantom{x}y" },
  { id: "vertical-phantom", command: "\\vphantom{\\frac{a}{b}}x", previewTex: "\\vphantom{\\frac{a}{b}}x" },
  { id: "smash", command: "\\smash{\\frac{a}{b}}", previewTex: "\\smash{\\frac{a}{b}}" },
  { id: "text", command: "\\text{条件}", previewTex: "\\text{条件}" },
  { id: "mathrm", command: "\\mathrm{cm}", previewTex: "\\mathrm{cm}" },
  { id: "mathbf", command: "\\mathbf{v}", previewTex: "\\mathbf{v}" },
  { id: "mathit", command: "\\mathit{ABC}", previewTex: "\\mathit{ABC}" },
  { id: "mathsf", command: "\\mathsf{ABC}", previewTex: "\\mathsf{ABC}" },
  { id: "mathtt", command: "\\mathtt{ABC}", previewTex: "\\mathtt{ABC}" },
  { id: "mathbb", command: "\\mathbb{R}", previewTex: "\\mathbb{R}" },
  { id: "mathcal", command: "\\mathcal{F}", previewTex: "\\mathcal{F}" },
  { id: "mathfrak", command: "\\mathfrak{g}", previewTex: "\\mathfrak{g}" },
  { id: "mathnormal", command: "\\mathnormal{x}", previewTex: "\\mathnormal{x}" },
  { id: "bold-symbol", command: "\\boldsymbol{\\alpha}", previewTex: "\\boldsymbol{\\alpha}" },
  { id: "operatorname", command: "\\operatorname{rank} A", previewTex: "\\operatorname{rank} A" },
  { id: "natural-log", command: "\\ln x", previewTex: "\\ln x" },
  { id: "exponential", command: "\\exp x", previewTex: "\\exp x" },
  { id: "arcsine", command: "\\arcsin x", previewTex: "\\arcsin x" },
  { id: "arccosine", command: "\\arccos x", previewTex: "\\arccos x" },
  { id: "arctangent", command: "\\arctan x", previewTex: "\\arctan x" },
  { id: "sinh", command: "\\sinh x", previewTex: "\\sinh x" },
  { id: "cosh", command: "\\cosh x", previewTex: "\\cosh x" },
  { id: "tanh", command: "\\tanh x", previewTex: "\\tanh x" },
  { id: "maximum", command: "\\max_{x} f(x)", previewTex: "\\max_{x} f(x)" },
  { id: "minimum", command: "\\min_{x} f(x)", previewTex: "\\min_{x} f(x)" },
  { id: "supremum", command: "\\sup A", previewTex: "\\sup A" },
  { id: "infimum", command: "\\inf A", previewTex: "\\inf A" },
  { id: "determinant", command: "\\det A", previewTex: "\\det A" },
  { id: "argument", command: "\\arg z", previewTex: "\\arg z" },
  { id: "secant", command: "\\sec x", previewTex: "\\sec x" },
  { id: "cosecant", command: "\\csc x", previewTex: "\\csc x" },
  { id: "cotangent", command: "\\cot x", previewTex: "\\cot x" },
  { id: "greatest-common-divisor", command: "\\gcd(a,b)", previewTex: "\\gcd(a,b)" },
  { id: "kernel", command: "\\ker T", previewTex: "\\ker T" },
  { id: "dimension", command: "\\dim V", previewTex: "\\dim V" },
  { id: "degree-operator", command: "\\deg f", previewTex: "\\deg f" },
  { id: "parenthesized-modulo", command: "a\\equiv b\\pmod{n}", previewTex: "a\\equiv b\\pmod{n}" },
  { id: "zeta", command: "\\zeta", previewTex: "\\zeta" },
  { id: "eta", command: "\\eta", previewTex: "\\eta" },
  { id: "iota", command: "\\iota", previewTex: "\\iota" },
  { id: "kappa", command: "\\kappa", previewTex: "\\kappa" },
  { id: "mu", command: "\\mu", previewTex: "\\mu" },
  { id: "nu", command: "\\nu", previewTex: "\\nu" },
  { id: "xi", command: "\\xi", previewTex: "\\xi" },
  { id: "rho", command: "\\rho", previewTex: "\\rho" },
  { id: "tau", command: "\\tau", previewTex: "\\tau" },
  { id: "upsilon", command: "\\upsilon", previewTex: "\\upsilon" },
  { id: "chi", command: "\\chi", previewTex: "\\chi" },
  { id: "psi", command: "\\psi", previewTex: "\\psi" },
  { id: "varepsilon", command: "\\varepsilon", previewTex: "\\varepsilon" },
  { id: "vartheta", command: "\\vartheta", previewTex: "\\vartheta" },
  { id: "varphi", command: "\\varphi", previewTex: "\\varphi" },
  { id: "varrho", command: "\\varrho", previewTex: "\\varrho" },
  { id: "varsigma", command: "\\varsigma", previewTex: "\\varsigma" },
  { id: "capital-gamma", command: "\\Gamma", previewTex: "\\Gamma" },
  { id: "capital-delta", command: "\\Delta", previewTex: "\\Delta" },
  { id: "capital-theta", command: "\\Theta", previewTex: "\\Theta" },
  { id: "capital-lambda", command: "\\Lambda", previewTex: "\\Lambda" },
  { id: "capital-xi", command: "\\Xi", previewTex: "\\Xi" },
  { id: "capital-pi", command: "\\Pi", previewTex: "\\Pi" },
  { id: "capital-sigma", command: "\\Sigma", previewTex: "\\Sigma" },
  { id: "capital-upsilon", command: "\\Upsilon", previewTex: "\\Upsilon" },
  { id: "capital-phi", command: "\\Phi", previewTex: "\\Phi" },
  { id: "capital-psi", command: "\\Psi", previewTex: "\\Psi" },
  { id: "capital-omega", command: "\\Omega", previewTex: "\\Omega" },
  { id: "approximately", command: "a\\approx b", previewTex: "a\\approx b" },
  { id: "similar", command: "A\\sim B", previewTex: "A\\sim B" },
  { id: "simeq", command: "a\\simeq b", previewTex: "a\\simeq b" },
  { id: "congruent", command: "A\\cong B", previewTex: "A\\cong B" },
  { id: "identical", command: "a\\equiv b", previewTex: "a\\equiv b" },
  { id: "proportional", command: "a\\propto b", previewTex: "a\\propto b" },
  { id: "parallel", command: "a\\parallel b", previewTex: "a\\parallel b" },
  { id: "perpendicular", command: "a\\perp b", previewTex: "a\\perp b" },
  { id: "divides", command: "a\\mid b", previewTex: "a\\mid b" },
  { id: "not-divides", command: "a\\nmid b", previewTex: "a\\nmid b" },
  { id: "much-less", command: "a\\ll b", previewTex: "a\\ll b" },
  { id: "much-greater", command: "a\\gg b", previewTex: "a\\gg b" },
  { id: "precedes", command: "a\\prec b", previewTex: "a\\prec b" },
  { id: "precedes-or-equal", command: "a\\preceq b", previewTex: "a\\preceq b" },
  { id: "succeeds", command: "a\\succ b", previewTex: "a\\succ b" },
  { id: "succeeds-or-equal", command: "a\\succeq b", previewTex: "a\\succeq b" },
  { id: "entails", command: "P\\models Q", previewTex: "P\\models Q" },
  { id: "proves", command: "P\\vdash Q", previewTex: "P\\vdash Q" },
  { id: "dot-equals", command: "a\\doteq b", previewTex: "a\\doteq b" },
  { id: "asymptotically-equal", command: "a\\asymp b", previewTex: "a\\asymp b" },
  { id: "less-or-similar", command: "a\\lesssim b", previewTex: "a\\lesssim b" },
  { id: "greater-or-similar", command: "a\\gtrsim b", previewTex: "a\\gtrsim b" },
  { id: "less-or-approximately", command: "a\\lessapprox b", previewTex: "a\\lessapprox b" },
  { id: "greater-or-approximately", command: "a\\gtrapprox b", previewTex: "a\\gtrapprox b" },
  { id: "triangle-equals", command: "a\\triangleq b", previewTex: "a\\triangleq b" },
  { id: "bowtie-relation", command: "A\\bowtie B", previewTex: "A\\bowtie B" },
  { id: "smile-relation", command: "A\\smile B", previewTex: "A\\smile B" },
  { id: "frown-relation", command: "A\\frown B", previewTex: "A\\frown B" },
  { id: "center-dot", command: "a\\cdot b", previewTex: "a\\cdot b" },
  { id: "asterisk", command: "a\\ast b", previewTex: "a\\ast b" },
  { id: "star", command: "a\\star b", previewTex: "a\\star b" },
  { id: "composition", command: "f\\circ g", previewTex: "f\\circ g" },
  { id: "bullet", command: "a\\bullet b", previewTex: "a\\bullet b" },
  { id: "direct-sum", command: "A\\oplus B", previewTex: "A\\oplus B" },
  { id: "ominus", command: "a\\ominus b", previewTex: "a\\ominus b" },
  { id: "tensor-product", command: "A\\otimes B", previewTex: "A\\otimes B" },
  { id: "oslash", command: "a\\oslash b", previewTex: "a\\oslash b" },
  { id: "modulo", command: "a\\bmod n", previewTex: "a\\bmod n" },
  { id: "minus-plus", command: "x=\\mp1", previewTex: "x=\\mp1" },
  { id: "big-direct-sum", command: "\\bigoplus_{i=1}^{n} V_i", previewTex: "\\bigoplus_{i=1}^{n} V_i" },
  { id: "big-tensor-product", command: "\\bigotimes_{i=1}^{n} V_i", previewTex: "\\bigotimes_{i=1}^{n} V_i" },
  { id: "coproduct", command: "\\coprod_{i=1}^{n} A_i", previewTex: "\\coprod_{i=1}^{n} A_i" },
  { id: "diamond-operator", command: "a\\diamond b", previewTex: "a\\diamond b" },
  { id: "large-up-triangle", command: "a\\bigtriangleup b", previewTex: "a\\bigtriangleup b" },
  { id: "large-down-triangle", command: "a\\bigtriangledown b", previewTex: "a\\bigtriangledown b" },
  { id: "triangle-left", command: "A\\triangleleft B", previewTex: "A\\triangleleft B" },
  { id: "triangle-right", command: "A\\triangleright B", previewTex: "A\\triangleright B" },
  { id: "wreath-product", command: "A\\wr B", previewTex: "A\\wr B" },
  { id: "amalgamation", command: "A\\amalg B", previewTex: "A\\amalg B" },
  { id: "circled-dot", command: "A\\odot B", previewTex: "A\\odot B" },
  { id: "big-circled-dot", command: "\\bigodot_{i=1}^{n} A_i", previewTex: "\\bigodot_{i=1}^{n} A_i" },
  { id: "big-multiset-union", command: "\\biguplus_{i=1}^{n} A_i", previewTex: "\\biguplus_{i=1}^{n} A_i" },
  { id: "big-square-union", command: "\\bigsqcup_{i=1}^{n} A_i", previewTex: "\\bigsqcup_{i=1}^{n} A_i" },
  { id: "big-logical-or", command: "\\bigvee_{i=1}^{n} P_i", previewTex: "\\bigvee_{i=1}^{n} P_i" },
  { id: "big-logical-and", command: "\\bigwedge_{i=1}^{n} P_i", previewTex: "\\bigwedge_{i=1}^{n} P_i" },
  { id: "empty-set", command: "\\emptyset", previewTex: "\\emptyset" },
  { id: "subset", command: "A\\subset B", previewTex: "A\\subset B" },
  { id: "subset-or-equal", command: "A\\subseteq B", previewTex: "A\\subseteq B" },
  { id: "superset", command: "A\\supset B", previewTex: "A\\supset B" },
  { id: "superset-or-equal", command: "A\\supseteq B", previewTex: "A\\supseteq B" },
  { id: "set-minus", command: "A\\setminus B", previewTex: "A\\setminus B" },
  { id: "for-all", command: "\\forall x", previewTex: "\\forall x" },
  { id: "exists", command: "\\exists x", previewTex: "\\exists x" },
  { id: "not-exists", command: "\\nexists x", previewTex: "\\nexists x" },
  { id: "logical-not", command: "\\neg P", previewTex: "\\neg P" },
  { id: "logical-and", command: "P\\land Q", previewTex: "P\\land Q" },
  { id: "logical-or", command: "P\\lor Q", previewTex: "P\\lor Q" },
  { id: "therefore", command: "\\therefore P", previewTex: "\\therefore P" },
  { id: "because", command: "\\because P", previewTex: "\\because P" },
  { id: "contains-element", command: "A\\ni x", previewTex: "A\\ni x" },
  { id: "not-subset", command: "A\\not\\subset B", previewTex: "A\\not\\subset B" },
  { id: "proper-subset", command: "A\\subsetneq B", previewTex: "A\\subsetneq B" },
  { id: "proper-superset", command: "A\\supsetneq B", previewTex: "A\\supsetneq B" },
  { id: "square-subset", command: "A\\sqsubset B", previewTex: "A\\sqsubset B" },
  { id: "square-subset-equal", command: "A\\sqsubseteq B", previewTex: "A\\sqsubseteq B" },
  { id: "square-superset", command: "A\\sqsupset B", previewTex: "A\\sqsupset B" },
  { id: "square-superset-equal", command: "A\\sqsupseteq B", previewTex: "A\\sqsupseteq B" },
  { id: "natural-numbers", command: "\\mathbb{N}", previewTex: "\\mathbb{N}" },
  { id: "integers", command: "\\mathbb{Z}", previewTex: "\\mathbb{Z}" },
  { id: "rational-numbers", command: "\\mathbb{Q}", previewTex: "\\mathbb{Q}" },
  { id: "real-numbers", command: "\\mathbb{R}", previewTex: "\\mathbb{R}" },
  { id: "complex-numbers", command: "\\mathbb{C}", previewTex: "\\mathbb{C}" },
  { id: "left-arrow", command: "A\\leftarrow B", previewTex: "A\\leftarrow B" },
  { id: "left-right-arrow", command: "A\\leftrightarrow B", previewTex: "A\\leftrightarrow B" },
  { id: "long-right-arrow", command: "A\\longrightarrow B", previewTex: "A\\longrightarrow B" },
  { id: "long-left-arrow", command: "A\\longleftarrow B", previewTex: "A\\longleftarrow B" },
  { id: "mapsto", command: "x\\mapsto f(x)", previewTex: "x\\mapsto f(x)" },
  { id: "hook-right-arrow", command: "A\\hookrightarrow B", previewTex: "A\\hookrightarrow B" },
  { id: "up-arrow", command: "\\uparrow", previewTex: "\\uparrow" },
  { id: "down-arrow", command: "\\downarrow", previewTex: "\\downarrow" },
  { id: "up-down-arrow", command: "\\updownarrow", previewTex: "\\updownarrow" },
  { id: "double-left-arrow", command: "A\\Leftarrow B", previewTex: "A\\Leftarrow B" },
  { id: "long-double-right-arrow", command: "A\\Longrightarrow B", previewTex: "A\\Longrightarrow B" },
  { id: "long-double-both-arrow", command: "A\\Longleftrightarrow B", previewTex: "A\\Longleftrightarrow B" },
  { id: "north-east-arrow", command: "\\nearrow", previewTex: "\\nearrow" },
  { id: "south-east-arrow", command: "\\searrow", previewTex: "\\searrow" },
  { id: "south-west-arrow", command: "\\swarrow", previewTex: "\\swarrow" },
  { id: "north-west-arrow", command: "\\nwarrow", previewTex: "\\nwarrow" },
  { id: "long-both-arrow", command: "A\\longleftrightarrow B", previewTex: "A\\longleftrightarrow B" },
  { id: "long-double-left-arrow", command: "A\\Longleftarrow B", previewTex: "A\\Longleftarrow B" },
  { id: "two-head-right-arrow", command: "A\\twoheadrightarrow B", previewTex: "A\\twoheadrightarrow B" },
  { id: "two-head-left-arrow", command: "A\\twoheadleftarrow B", previewTex: "A\\twoheadleftarrow B" },
  { id: "right-arrow-tail", command: "A\\rightarrowtail B", previewTex: "A\\rightarrowtail B" },
  { id: "left-arrow-tail", command: "A\\leftarrowtail B", previewTex: "A\\leftarrowtail B" },
  { id: "wavy-right-arrow", command: "A\\rightsquigarrow B", previewTex: "A\\rightsquigarrow B" },
  { id: "wavy-both-arrow", command: "A\\leftrightsquigarrow B", previewTex: "A\\leftrightsquigarrow B" },
  { id: "right-harpoon-up", command: "A\\rightharpoonup B", previewTex: "A\\rightharpoonup B" },
  { id: "right-harpoon-down", command: "A\\rightharpoondown B", previewTex: "A\\rightharpoondown B" },
  { id: "left-harpoon-up", command: "A\\leftharpoonup B", previewTex: "A\\leftharpoonup B" },
  { id: "left-harpoon-down", command: "A\\leftharpoondown B", previewTex: "A\\leftharpoondown B" },
  { id: "equilibrium-arrows", command: "A\\rightleftharpoons B", previewTex: "A\\rightleftharpoons B" },
  { id: "partial", command: "\\frac{\\partial f}{\\partial x}", previewTex: "\\frac{\\partial f}{\\partial x}" },
  { id: "nabla", command: "\\nabla f", previewTex: "\\nabla f" },
  { id: "double-integral", command: "\\iint_D f\\,dA", previewTex: "\\iint_D f\\,dA" },
  { id: "triple-integral", command: "\\iiint_V f\\,dV", previewTex: "\\iiint_V f\\,dV" },
  { id: "contour-integral", command: "\\oint_C f\\,dz", previewTex: "\\oint_C f\\,dz" },
  { id: "limit-superior", command: "\\limsup_{n\\to\\infty} a_n", previewTex: "\\limsup_{n\\to\\infty} a_n" },
  { id: "limit-inferior", command: "\\liminf_{n\\to\\infty} a_n", previewTex: "\\liminf_{n\\to\\infty} a_n" },
  { id: "ordinary-derivative", command: "\\frac{dy}{dx}", previewTex: "\\frac{dy}{dx}" },
  { id: "second-derivative", command: "\\frac{d^2y}{dx^2}", previewTex: "\\frac{d^2y}{dx^2}" },
  { id: "evaluation-bar", command: "\\left.F(x)\\right|_{a}^{b}", previewTex: "\\left.F(x)\\right|_{a}^{b}" },
  { id: "sum-with-multiple-conditions", command: "\\sum_{\\begin{smallmatrix}1\\leq i\\leq n\\\\i\\text{は奇数}\\end{smallmatrix}} i", previewTex: "\\sum_{\\begin{smallmatrix}1\\leq i\\leq n\\\\i\\text{は奇数}\\end{smallmatrix}} i" },
  { id: "integral-with-limits", command: "\\int\\limits_{a}^{b} f(x)\\,dx", previewTex: "\\int\\limits_{a}^{b} f(x)\\,dx" },
  { id: "big-union", command: "\\bigcup_{i=1}^{n} A_i", previewTex: "\\bigcup_{i=1}^{n} A_i" },
  { id: "big-intersection", command: "\\bigcap_{i=1}^{n} A_i", previewTex: "\\bigcap_{i=1}^{n} A_i" },
  { id: "angle", command: "\\angle ABC", previewTex: "\\angle ABC" },
  { id: "measured-angle", command: "\\measuredangle ABC", previewTex: "\\measuredangle ABC" },
  { id: "triangle", command: "\\triangle ABC", previewTex: "\\triangle ABC" },
  { id: "directed-segment", command: "\\overrightarrow{AB}", previewTex: "\\overrightarrow{AB}" },
  { id: "line-through-points", command: "\\overleftrightarrow{AB}", previewTex: "\\overleftrightarrow{AB}" },
  { id: "probability", command: "\\Pr(A)", previewTex: "\\Pr(A)" },
  { id: "conditional-probability", command: "P(A\\mid B)", previewTex: "P(A\\mid B)" },
  { id: "expectation", command: "\\mathbb{E}[X]", previewTex: "\\mathbb{E}[X]" },
  { id: "variance", command: "\\operatorname{Var}(X)", previewTex: "\\operatorname{Var}(X)" },
  { id: "covariance", command: "\\operatorname{Cov}(X,Y)", previewTex: "\\operatorname{Cov}(X,Y)" },
  { id: "combination", command: "_{n}\\mathrm{C}_{r}", previewTex: "_{n}\\mathrm{C}_{r}" },
  { id: "permutation", command: "_{n}\\mathrm{P}_{r}", previewTex: "_{n}\\mathrm{P}_{r}" },
  { id: "repeated-combination", command: "_{n}\\mathrm{H}_{r}", previewTex: "_{n}\\mathrm{H}_{r}" },
  { id: "factorial", command: "n!", previewTex: "n!" },
  { id: "bar", command: "\\bar{x}", previewTex: "\\bar{x}" },
  { id: "underline", command: "\\underline{AB}", previewTex: "\\underline{AB}" },
  { id: "wide-hat", command: "\\widehat{ABC}", previewTex: "\\widehat{ABC}" },
  { id: "tilde", command: "\\tilde{x}", previewTex: "\\tilde{x}" },
  { id: "wide-tilde", command: "\\widetilde{ABC}", previewTex: "\\widetilde{ABC}" },
  { id: "dot", command: "\\dot{x}", previewTex: "\\dot{x}" },
  { id: "double-dot", command: "\\ddot{x}", previewTex: "\\ddot{x}" },
  { id: "overbrace", command: "\\overbrace{a+b+c}^{3項}", previewTex: "\\overbrace{a+b+c}^{3項}" },
  { id: "underbrace", command: "\\underbrace{a+b+c}_{3項}", previewTex: "\\underbrace{a+b+c}_{3項}" },
  { id: "real-part", command: "\\Re z", previewTex: "\\Re z" },
  { id: "imaginary-part", command: "\\Im z", previewTex: "\\Im z" },
  { id: "script-ell", command: "\\ell", previewTex: "\\ell" },
  { id: "reduced-planck", command: "\\hbar", previewTex: "\\hbar" },
  { id: "aleph", command: "\\aleph", previewTex: "\\aleph" },
  { id: "beth", command: "\\beth", previewTex: "\\beth" },
  { id: "dotless-i", command: "\\imath", previewTex: "\\imath" },
  { id: "dotless-j", command: "\\jmath", previewTex: "\\jmath" },
  { id: "weierstrass-p", command: "\\wp", previewTex: "\\wp" },
  { id: "prime-symbol", command: "x^{\\prime}", previewTex: "x^{\\prime}" },
  { id: "back-prime", command: "\\backprime", previewTex: "\\backprime" },
  { id: "dagger", command: "A^{\\dagger}", previewTex: "A^{\\dagger}" },
  { id: "double-dagger", command: "A^{\\ddagger}", previewTex: "A^{\\ddagger}" },
  { id: "acute-accent", command: "\\acute{x}", previewTex: "\\acute{x}" },
  { id: "grave-accent", command: "\\grave{x}", previewTex: "\\grave{x}" },
  { id: "breve-accent", command: "\\breve{x}", previewTex: "\\breve{x}" },
  { id: "check-accent", command: "\\check{x}", previewTex: "\\check{x}" },
  { id: "ring-accent", command: "\\mathring{x}", previewTex: "\\mathring{x}" },
  { id: "left-vector", command: "\\overleftarrow{AB}", previewTex: "\\overleftarrow{AB}" },
  { id: "braces", command: "\\left\\{x+1\\right\\}", previewTex: "\\left\\{x+1\\right\\}" },
  { id: "square-brackets", command: "\\left[x+1\\right]", previewTex: "\\left[x+1\\right]" },
  { id: "angle-brackets", command: "\\left\\langle x,y\\right\\rangle", previewTex: "\\left\\langle x,y\\right\\rangle" },
  { id: "floor", command: "\\left\\lfloor x\\right\\rfloor", previewTex: "\\left\\lfloor x\\right\\rfloor" },
  { id: "ceiling", command: "\\left\\lceil x\\right\\rceil", previewTex: "\\left\\lceil x\\right\\rceil" },
  { id: "norm", command: "\\left\\lVert x\\right\\rVert", previewTex: "\\left\\lVert x\\right\\rVert" },
  { id: "brace-delimiters", command: "\\left\\lbrace x\\right\\rbrace", previewTex: "\\left\\lbrace x\\right\\rbrace" },
  { id: "vertical-delimiters", command: "\\left\\lvert x\\right\\rvert", previewTex: "\\left\\lvert x\\right\\rvert" },
  { id: "double-vertical-delimiters", command: "\\left\\lVert x\\right\\rVert", previewTex: "\\left\\lVert x\\right\\rVert" },
  { id: "low-dots", command: "a_1,\\ldots,a_n", previewTex: "a_1,\\ldots,a_n" },
  { id: "center-dots", command: "a_1+\\cdots+a_n", previewTex: "a_1+\\cdots+a_n" },
  { id: "vertical-dots", command: "\\vdots", previewTex: "\\vdots" },
  { id: "diagonal-dots", command: "\\ddots", previewTex: "\\ddots" },
  { id: "thin-space", command: "a\\,b", previewTex: "a\\,b" },
  { id: "medium-space", command: "a\\;b", previewTex: "a\\;b" },
  { id: "quad-space", command: "a\\quad b", previewTex: "a\\quad b" },
  { id: "double-quad-space", command: "a\\qquad b", previewTex: "a\\qquad b" },
  { id: "negative-space", command: "a\\!b", previewTex: "a\\!b" },
  { id: "colon-relation", command: "f\\colon A\\to B", previewTex: "f\\colon A\\to B" },
  { id: "matrix-plain", command: "\\begin{matrix}a&b\\\\c&d\\end{matrix}", previewTex: "\\begin{matrix}a&b\\\\c&d\\end{matrix}" },
  { id: "matrix-brackets", command: "\\begin{bmatrix}a&b\\\\c&d\\end{bmatrix}", previewTex: "\\begin{bmatrix}a&b\\\\c&d\\end{bmatrix}" },
  { id: "matrix-braces", command: "\\begin{Bmatrix}a&b\\\\c&d\\end{Bmatrix}", previewTex: "\\begin{Bmatrix}a&b\\\\c&d\\end{Bmatrix}" },
  { id: "determinant-bars", command: "\\begin{vmatrix}a&b\\\\c&d\\end{vmatrix}", previewTex: "\\begin{vmatrix}a&b\\\\c&d\\end{vmatrix}" },
  { id: "determinant-double-bars", command: "\\begin{Vmatrix}a&b\\\\c&d\\end{Vmatrix}", previewTex: "\\begin{Vmatrix}a&b\\\\c&d\\end{Vmatrix}" },
  { id: "small-matrix", command: "\\begin{smallmatrix}a&b\\\\c&d\\end{smallmatrix}", previewTex: "\\begin{smallmatrix}a&b\\\\c&d\\end{smallmatrix}" },
  { id: "aligned", command: "\\begin{aligned}x+y&=3\\\\x-y&=1\\end{aligned}", previewTex: "\\begin{aligned}x+y&=3\\\\x-y&=1\\end{aligned}" },
  { id: "aligned-multiple", command: "\\begin{aligned}x&=1&\\quad y&=2\\end{aligned}", previewTex: "\\begin{aligned}x&=1&\\quad y&=2\\end{aligned}" },
  { id: "array", command: "\\begin{array}{c|c}x&y\\\\1&2\\end{array}", previewTex: "\\begin{array}{c|c}x&y\\\\1&2\\end{array}" },
  { id: "equation-array", command: "\\begin{array}{rcl}x&=&1\\\\y&=&2\\end{array}", previewTex: "\\begin{array}{rcl}x&=&1\\\\y&=&2\\end{array}" },
  { id: "gathered", command: "\\begin{gathered}a+b=c\\\\x+y=z\\end{gathered}", previewTex: "\\begin{gathered}a+b=c\\\\x+y=z\\end{gathered}" },
  { id: "column-vector", command: "\\begin{pmatrix}x\\\\y\\\\z\\end{pmatrix}", previewTex: "\\begin{pmatrix}x\\\\y\\\\z\\end{pmatrix}" },
  { id: "row-vector", command: "\\begin{pmatrix}x&y&z\\end{pmatrix}", previewTex: "\\begin{pmatrix}x&y&z\\end{pmatrix}" },
  { id: "augmented-matrix", command: "\\left(\\begin{array}{cc|c}1&2&3\\\\4&5&6\\end{array}\\right)", previewTex: "\\left(\\begin{array}{cc|c}1&2&3\\\\4&5&6\\end{array}\\right)" },
  { id: "system-array", command: "\\left\\{\\begin{array}{rcl}x+y&=&3\\\\x-y&=&1\\end{array}\\right.", previewTex: "\\left\\{\\begin{array}{rcl}x+y&=&3\\\\x-y&=&1\\end{array}\\right." },
] as const;

export const TEX_COMMAND_REFERENCE_IDS = TEX_COMMAND_REFERENCE_DESCRIPTORS.map(({ id }) => id);

export function resolveTexCommandReferences(
  t: Translate<"tex"> = DEFAULT_TEX_TRANSLATE,
): readonly TexCommandReference[] {
  // The reference ids are generated from this module's descriptor table, while
  // i18next's key union is generated from the dictionary. Keep that runtime
  // boundary explicit instead of casting a dynamic key to `never` (which also
  // makes the translated result `never`).
  const translateReference = t as unknown as (key: string) => string;
  return TEX_COMMAND_REFERENCE_DESCRIPTORS.map((reference) => {
    const localizedExample = LOCALIZED_EXAMPLE_IDS.has(reference.id)
      ? {
          command: translateReference(`localizedExample.${reference.id}.command`),
          previewTex: translateReference(`localizedExample.${reference.id}.previewTex`),
        }
      : null;
    return {
      ...reference,
      ...localizedExample,
      category: translateReference(`reference.${reference.id}.category`),
      label: translateReference(`reference.${reference.id}.label`),
      keywords: translateReference(`reference.${reference.id}.keywords`)
        .split(KEYWORD_SEPARATOR)
        .map((keyword) => keyword.trim())
        .filter(Boolean),
    };
  });
}

/** Japanese-default compatibility snapshot for non-reactive callers. */
export const TEX_COMMAND_REFERENCES: readonly TexCommandReference[] = resolveTexCommandReferences();

function normalizeTexCommandSearchText(value: string): string {
  return value
    .normalize("NFKC")
    .replace(/[￥¥]/g, "\\")
    .trim()
    .toLocaleLowerCase();
}

/** Searches localized names/categories/keywords together with stable TeX commands and aliases. */
export function filterTexCommandReferences(
  query: string,
  t: Translate<"tex"> = DEFAULT_TEX_TRANSLATE,
): readonly TexCommandReference[] {
  const normalizedQuery = normalizeTexCommandSearchText(query);
  const references = resolveTexCommandReferences(t);
  if (!normalizedQuery) {
    return references;
  }

  return references.filter((reference) => {
    const searchText = normalizeTexCommandSearchText([
      reference.category,
      reference.label,
      reference.id.replaceAll("-", " "),
      reference.command,
      reference.previewTex,
      ...(reference.aliases ?? []),
      ...reference.keywords,
    ].join(" "));
    return searchText.includes(normalizedQuery);
  });
}
