// Generated by scripts/generate-document-types.mjs from features/document. Do not edit.

export type SigmaBlock = SectionNode | HeadingNode | ParagraphNode | ListNode | QuoteBlockNode | CodeBlockNode | DividerNode | ProblemNode | LayoutSectionNode | BoxBlockNode;

/**
 * 文章を持つブロック。`divider` は意図的に入れていない — ヘッダー/フッター (`PageRunningRegion`)
 * はこの型で組まれていて、ページごとに複製・採寸される領域に「中身の無いブロック」を通すと
 * `children` を前提にした経路がそこでも分岐を持つ。罫線が要るなら図形で引ける。
 */
export type RichBlock = HeadingNode | ParagraphNode | ListNode;

export type ProblemAreaBlock = RichBlock | QuoteBlockNode | CodeBlockNode | DividerNode | LayoutSectionNode | BoxBlockNode;

export type LayoutSectionChildBlock = SectionNode | HeadingNode | ParagraphNode | ListNode | QuoteBlockNode | CodeBlockNode | DividerNode | BoxBlockNode;

/** 枠は任意の文書ブロックを包める。改ページも子の pagination で表す。 */
export type BoxBlockChildBlock = SigmaBlock;

/**
 * 引用の中に置けるもの。入れ子の引用と段組・囲み枠は入れていない — 引用は「本文を一段
 * 引き込む」ための入れ物で、その中でページ割りの単位をもう一段作る意味が無い。
 * 必要になったらここに 1 行足す (中身の描画は子ブロックの経路をそのまま通る)。
 */
export type QuoteChildBlock = HeadingNode | ParagraphNode | ListNode | CodeBlockNode | DividerNode;

export interface BaseNode {
    type: string;
    id: string;
    pagination?: PaginationHints;
    /**
     * ブロック最終行の下に足す CSS px (0..400 の整数、ズーム非依存の論理 px)。
     * 未指定は 0 と同じ = 従来どおりの間隔。`padding-bottom` として描くので実測の高さに含まれる。
     */
    spaceAfterPx?: number;
}

export interface PaginationHints {
    break?: boolean;
    keepTogether?: boolean;
    keepWithNext?: boolean;
}

export interface SectionNode extends BaseNode {
    type: "section";
    title: string;
    align?: TextAlign;
    lineHeight?: LineHeight;
}

export interface HeadingNode extends BaseNode {
    type: "heading";
    level: 1 | 2 | 3;
    children: InlineNode[];
    align?: TextAlign;
    lineHeight?: LineHeight;
}

export interface ParagraphNode extends BaseNode {
    type: "paragraph";
    children: InlineNode[];
    align?: TextAlign;
    lineHeight?: LineHeight;
}

/**
 * 引用ブロック。本文ブロックを一段引き込んで見せる入れ物 (HTML の `blockquote` と同じ)。
 *
 * 中身が複数行になっても縦棒は **ブロック 1 つに 1 本** 引く。段落ごとに引くと、チャンク境界・
 * 改ページウィジェット・段組の絶対配置が間に入った瞬間に繋ぎ目が割れる。
 */
export interface QuoteBlockNode extends BaseNode {
    type: "quote";
    blocks: QuoteChildBlock[];
}

/**
 * コードブロック。改行を含む **1 つの** テキストブロック。
 *
 * 段落の連なりではなく 1 ブロックなので、中の行間は常に一定で、箱も 1 つ。改行は他の本文と
 * 同じ規約で text run の中の `\n` として持つ (編集面では hardBreak)。
 * 文字単位の書式は `children` の run が持つので、フォント・大きさ・色はそのまま変えられる。
 */
export interface CodeBlockNode extends BaseNode {
    type: "codeBlock";
    children: InlineNode[];
    /**
     * 色分けに使う言語。未指定は自動判定。
     *
     * 値は highlight.js の登録名そのもの（`features/rendering/adapters/code-highlight.ts` の一覧）。
     * 色そのものは保存しない — トークンは毎回引き直す派生値で、これにより編集中・静的描画・
     * 印刷/PDF・埋め込みビューアが同じ関数から同じ色を出せる。
     */
    language?: string;
    /**
     * コードブロックだけの配色。未指定はライト。
     *
     * アプリ全体のテーマとは独立したブロック設定として保存し、編集面・印刷・ビューアの全てで
     * 同じ背景と構文色を使う。背景色そのものを保存しないので、配色の調整で文書を書き換えずに済む。
     */
    theme?: CodeBlockTheme;
}

export type CodeBlockTheme = "light" | "dark";

export declare function normalizeCodeBlockTheme(value: unknown): CodeBlockTheme | undefined;

/** 区切り線。中身を持たない唯一の本文ブロック。 */
export interface DividerNode extends BaseNode {
    type: "divider";
}

/**
 * How an ordered list draws its number. Adding a近い形式 (全角括弧など) means adding one value
 * here plus one input rule and one counter style — `listType` stays `"ordered"` so every existing
 * `listType === "ordered"` branch keeps working.
 */
export type OrderedListMarkerStyle = "decimal" | "paren";

/**
 * 1 つの項目マーカーの下にぶら下がるブロック。
 *
 * 区切り線も置ける — 項目の中で話題を切りたいことは普通にあり、置けないほうが不自然だから。
 * 入れ物 (引用・囲み枠・段組) は入れない: 項目の中でページ割りの単位を増やすと、リストの
 * マーカー計算と入れ物のページまたぎが同時に効いて手に負えなくなる。
 *
 * `divider` は文章を持たない。項目の中身を読む側は `listItemContinuationInlineNodes` を通すこと。
 */
export type ListItemContinuationNode = HeadingNode | ParagraphNode | DividerNode;

export interface ListNode extends BaseNode {
    type: "list";
    listType: "bullet" | "ordered";
    start?: number;
    /** 番号マーカーの見せ方。未指定は "decimal"。"ordered" 以外では無視する。 */
    markerStyle?: OrderedListMarkerStyle;
    items: ListItemNode[];
}

export interface ListItemNode {
    type: "listItem";
    id: string;
    children: InlineNode[];
    align?: TextAlign;
    /** Extra space after this item. List items are independently draggable blocks in the editor. */
    spaceAfterPx?: number;
    /** Additional text blocks that stay under the same list marker. */
    continuations?: ListItemContinuationNode[];
    nested?: ListNode[];
}

export interface ProblemNode extends BaseNode {
    type: "problem";
    tags: string[];
    lead: ProblemAreaBlock[];
    prompt: ProblemAreaBlock[];
    answer?: AnswerDefinition;
    solution: ProblemAreaBlock[];
    hints: ProblemAreaBlock[];
    areaLayout?: Partial<Record<ProblemAreaKind, ProblemAreaLayout>>;
    numbering?: ProblemNumbering;
    frame?: ProblemFrame;
}

export type ProblemAreaKind = "lead" | "prompt" | "solution" | "hints";

/**
 * The order a problem's areas are laid out in on the page — 導入文 → 問題文 → コメント →
 * 解答. Note this is NOT the field order of `ProblemNode` (`solution` is declared before
 * `hints`), so anything walking areas for rendering, pagination or editing must use this
 * constant rather than iterating the interface.
 */
export declare const PROBLEM_AREA_ORDER: readonly ProblemAreaKind[];

/**
 * Unknown marker styles become `undefined` (= the implicit `"decimal"`) rather than being kept, so
 * an unrecognized value degrades to a plain numbered list instead of losing the list entirely.
 */
export declare function normalizeOrderedListMarkerStyle(value: unknown): OrderedListMarkerStyle | undefined;

export type ProblemAreaColumnSpan = "column" | "full";

export interface ProblemAreaLayout {
    minHeightMm?: number;
    columnSpan?: ProblemAreaColumnSpan;
}

export interface ProblemNumbering {
    enabled?: boolean;
    fontSize?: number;
    value?: number;
}

export interface ProblemFrame {
    enabled?: boolean;
    styleId?: string;
}

export interface LayoutSectionNode extends BaseNode {
    type: "layoutSection";
    layout: LayoutSectionLayout;
    children: LayoutSectionChildBlock[];
}

export interface LayoutSectionLayout {
    columnCount: number;
    columnGapMm?: number;
    columnRule?: ColumnRule;
    /**
     * Independent column ownership. Each entry is the id of the first child in that column,
     * ordered from left to right. Unlike `pagination.break`, this is layout structure rather than
     * pagination state, so editing one column can never cause its blocks to flow into another.
     */
    columnStartIds?: string[];
    /** Relative widths, ordered like `columnStartIds`. Values are normalized at render time. */
    columnWidths?: number[];
}

export interface BoxBlockNode extends BaseNode {
    type: "boxBlock";
    /** Built-in or user-defined style identifier such as `fancybox` or `doublebox`. */
    styleId: string;
    title?: InlineNode[];
    blocks: BoxBlockChildBlock[];
    frame?: BoxFrameSpec;
}

export interface BoxFrameSpec {
    borderWidthPx?: number;
    borderColor?: string;
    borderStyle?: "solid" | "dashed" | "dotted" | "double" | "none";
    backgroundColor?: string;
    titleBackgroundColor?: string;
    titleColor?: string;
    titleAlign?: TextAlign;
    titlePosition?: "l" | "c" | "r";
    titleFontWeight?: "normal" | "bold";
    titleFontFamily?: string;
    titleFontSizePx?: number;
    titleLineHeight?: string;
    bodyColor?: string;
    bodyAlign?: TextAlign;
    bodyFontFamily?: string;
    bodyFontSizePx?: number;
    bodyLineHeight?: string;
    cornerStyle?: "sharp" | "round";
    radiusPx?: number;
    paddingPx?: BoxSpacingPx;
    decorations?: BoxDecorationSpec[];
}

export interface BoxSpacingPx {
    top: number;
    right: number;
    bottom: number;
    left: number;
}

export type BoxDecorationSpec = {
    type: "cornerSquares";
    sizePx: number;
    color: string;
} | {
    type: "doubleRule";
    offsetPx: number;
    widthPx?: number;
    color?: string;
} | {
    type: "titleDoubleRule";
    ruleWidthPx?: number;
    ruleColor?: string;
    guideColor?: string;
} | {
    type: "titleBand";
    heightPx?: number;
    backgroundColor?: string;
    /** 帯と本文の境に引く罫。TeX の見出し付き枠が持つ「帯の下の 1 本」。 */
    ruleWidthPx?: number;
    ruleColor?: string;
}
/**
 * 枠の上辺に載せる見出しタブ (tcolorbox の `attach boxed title to top left` 相当)。
 * `titlePlate` と違って**地色で塗る**ので、タイトルの背景がそのまま見出しになる。
 */
 | {
    type: "titleTab";
    heightPx?: number;
    radiusPx?: number;
    offsetXPx?: number;
    paddingPx?: BoxSpacingPx;
    backgroundColor?: string;
} | {
    type: "titlePlate";
    borderColor?: string;
    radiusPx?: number;
    paddingPx?: BoxSpacingPx;
} | {
    type: "leftBar";
    widthPx: number;
    color: string;
} | {
    type: "shadow";
    offsetXPx: number;
    offsetYPx: number;
    blurPx?: number;
    spreadPx?: number;
    color: string;
} | {
    type: "horizontalRules";
    widthPx?: number;
    color?: string;
} | {
    type: "notebookRules";
    baseBodyWidthPx?: number;
    frameLeftPx?: number;
    frameHeightPx?: number;
    frameStrokeOpacity?: number;
    lineColor?: string;
    lineGapPx?: number;
    lineWidthPx?: number;
    lineOffsetPx?: number;
    bindingColor?: string;
    bindingWidthPx?: number;
    bindingXPx?: number;
    bindingStrokeOpacity?: number;
    ringColor?: string;
    ringWidthPx?: number;
    ringHeightPx?: number;
    ringStrokePx?: number;
    ringGapPx?: number;
    ringTopPx?: number;
    ringCount?: number;
    ringLeftOverhangPx?: number;
    minHeightPx?: number;
};

export interface AnswerDefinition {
    type: "math" | "text";
    expected: string;
}

/**
 * リスト項目の続きブロックが持つ文章。区切り線は持たないので空配列。
 *
 * 項目の中身を読む側 (検索・文字数・コピペ・AI 差分・行の計測) はこれを通す。`children` を
 * 直接触ると、区切り線を 1 つ足しただけで全経路が落ちる。
 */
export declare function listItemContinuationInlineNodes(block: ListItemContinuationNode): InlineNode[];

export type SigmaChartKind = "bar" | "line" | "pie" | "scatter";

/**
 * The author's intent for a chart. Everything here is chosen by a person; nothing is derived.
 *
 * The data a chart draws lives elsewhere on the shape — read live from the referenced table, or from
 * the snapshot when that table is gone — so a settings panel writing this object can never race the
 * snapshot sync for the same field.
 */
export interface SigmaChartSpec {
    version: 1;
    kind: SigmaChartKind;
    /**
     * Which axis of the table carries the series.
     *
     * `"columns"` (the default) reads the first row as headers and the first column as labels;
     * `"rows"` is the same reading of the transposed table, which is what the swap toggle flips.
     */
    orientation: "columns" | "rows";
    /** Treat the leading row (after any transpose) as series names rather than data. */
    headerRow: boolean;
    /** Treat the leading column (after any transpose) as category labels rather than data. */
    labelColumn: boolean;
    title?: string;
    legend: boolean;
    /**
     * Series colour keyed by the table's own `column.id` / `row.id`.
     *
     * Keying on the track id rather than the series index is what keeps a colour attached to its
     * entity: inserting or reordering a column leaves every existing series the colour it had.
     */
    seriesColors: Record<string, string>;
}

export interface SigmaChartSeries {
    /** The `column.id` / `row.id` the series was read from. Stable across edits to the table. */
    id: string;
    name: string;
    /** One entry per label. `null` marks a cell that held no number — a gap, not a zero. */
    values: (number | null)[];
}

/** Derived drawing input: also what a chart persists so it survives losing its table. */
export interface SigmaChartData {
    labels: string[];
    series: SigmaChartSeries[];
    /** Scatter only: the x coordinate of each point, parallel to `labels`. */
    xValues?: (number | null)[];
}

/**
 * Eight categorical colours that stay apart on white paper, drawn from the saturated band of the
 * shared palette so a chart sits with the other figures in a document rather than beside them.
 */
export declare const CHART_SERIES_PALETTE: readonly string[];

/**
 * Series past the eighth are grey on purpose. Cycling the palette would give two series the same
 * colour, which reads as "these are related" — a neutral says "too many to tell apart" instead.
 */
export declare const CHART_SERIES_FALLBACK_COLOR = "#737373";

/** A printed separator shared by every gap in its page flow or local section. */
export interface ColumnRule {
    style: "none" | "solid" | "dashed" | "dotted" | "double";
    widthPx: number;
    color: string;
}

export declare const DEFAULT_COLUMN_RULE: Readonly<ColumnRule>;

export declare function normalizeColumnRule(value: unknown): ColumnRule | undefined;

export interface SigmaCommentThread {
    id: string;
    anchor: SigmaCommentAnchor;
    messages: SigmaCommentMessage[];
    /** Thread-level reactions are displayed on the first message. */
    reactions?: SigmaCommentReaction[];
    resolved?: boolean;
    color?: string;
    createdAt: string;
    updatedAt?: string;
}

export interface SigmaCommentMessage {
    id: string;
    authorName?: string;
    /**
     * 差出人が AI の場合の素性。**人が書いたコメントには付けない** (欠けていること
     * そのものが「人が書いた」の意味になる)。表示側はここを見てベンダーのロゴを出す。
     */
    agent?: SigmaCommentAgent;
    body: InlineNode[];
    reactions?: SigmaCommentReaction[];
    createdAt: string;
    updatedAt?: string;
}

/**
 * コメントを書いた AI の提供元。ロゴを持つのは `openai` / `anthropic` / `google` /
 * `microsoft` の 4 つで、それ以外は汎用の AI バッジで描く (`comment-agents.ts`)。
 */
export declare const SIGMA_COMMENT_AGENT_VENDORS: readonly [
    "openai",
    "anthropic",
    "google",
    "microsoft",
    "meta",
    "xai",
    "mistral",
    "other"
];

export type SigmaCommentAgentVendor = typeof SIGMA_COMMENT_AGENT_VENDORS[number];

export interface SigmaCommentAgent {
    vendor: SigmaCommentAgentVendor;
    /** モデル名など、ベンダーより細かい表示 (例: "GPT-5")。表示は名前の下の小さな行。 */
    model?: string;
}

export interface SigmaCommentReaction {
    id: string;
    emoji: string;
    authorName?: string;
    createdAt: string;
}

export type SigmaCommentAnchor = SigmaTextRangeCommentAnchor | SigmaInlineMathCommentAnchor | SigmaBlockCommentAnchor | SigmaOverlayShapeCommentAnchor | SigmaOverlayMathCommentAnchor | SigmaCanvasRegionCommentAnchor;

export interface SigmaTextRangeCommentAnchor {
    type: "textRange";
    start: SigmaCommentTextPosition;
    end: SigmaCommentTextPosition;
    quote: string;
    mathInlineIds?: string[];
    mathTex?: string[];
}

export interface SigmaCommentTextPosition {
    blockId: string;
    offset: number;
}

export interface SigmaInlineMathCommentAnchor {
    type: "inlineMath";
    blockId: string;
    mathInlineId: string;
    quote?: string;
    tex?: string;
}

export interface SigmaBlockCommentAnchor {
    type: "block";
    blockId: string;
    quote?: string;
}

/** A fixed rectangle in absolute, unzoomed canvas coordinates, independent of shapes. */
export interface SigmaCanvasRegionCommentAnchor {
    type: "canvasRegion";
    bounds: {
        x: number;
        y: number;
        w: number;
        h: number;
    };
    quote?: string;
}

export interface SigmaOverlayShapeCommentAnchor {
    type: "overlayShape";
    shapeIds: string[];
    quote?: string;
}

export interface SigmaOverlayMathCommentAnchor {
    type: "overlayMath";
    shapeId?: string;
    mathInlineId?: string;
    quote?: string;
    tex?: string;
}

/**
 * コメントアンカーの値キー。**同じ位置・同じ引用なら同じ文字列**になる (アンカーはこの
 * アプリが組み立てるオブジェクトで、キーの順序は生成コードで固定されている)。
 */
export declare function getCommentAnchorKey(anchor: SigmaCommentAnchor | null | undefined): string;

/**
 * 候補アンカーの同値判定キー。**`block` のときだけ引用文を落とす**。
 *
 * `block` の引用はその段落の本文まるごとなので、1 文字打つだけで変わる。これを同値判定に
 * 入れると「同じ段落を指したまま」でも候補が作り直されたと判定され、画面全体が再描画される。
 * 落とした引用はコメントを作る瞬間に取り直す (`openCommentComposer`)。
 *
 * 他の種別 (テキスト選択・インライン数式・図形) の引用は選択範囲のスナップショットで、
 * 打鍵では作り直されない。ここで手を抜くと引用だけ古いコメントが保存されるので、完全一致で比べる。
 */
export declare function getCommentAnchorCandidateKey(anchor: SigmaCommentAnchor | null | undefined): string;

export type SigmaDocVersion = "2.0";

export type OutputProfileName = "student" | "teacher" | "answerBook";

export interface SigmaDocument {
    version: SigmaDocVersion;
    docId: string;
    metadata: SigmaMetadata;
    content: SigmaBlock[];
    outputProfiles: Record<OutputProfileName, OutputProfile>;
    comments?: SigmaCommentThread[];
    pageLayout?: PageLayout;
    updatedAt?: string;
}

export interface OutputProfile {
    showSolutions?: boolean;
    showHints?: boolean;
    includeAnswers?: boolean;
    onlySolutions?: boolean;
    includeComments?: boolean;
}

export interface GraphParameter {
    id: string;
    /** Identifier referenced from expressions, for example `s` in `z = s`. */
    name: string;
    label?: string;
    value: number;
    min: number;
    max: number;
    animation?: GraphParameterAnimation;
}

/**
 * Playback runs the parameter across its own `min`..`max`, so the range is stated once — as the
 * inequality the card shows — and never as a second pair of start/end numbers that could disagree.
 */
export interface GraphParameterAnimation {
    /** One pass from `min` to `max`. A ping-pong's return leg takes the same time again. */
    durationMs: number;
    loop: "once" | "repeat" | "pingPong";
    /**
     * Keep this parameter moving on the page, not only while the settings panel previews it.
     * 3D materials also keep this motion in their derived animated PNG preview.
     */
    playOnPage?: boolean;
}

export type Graph2DKind = "cartesian" | "numberLine";

export type Graph2DPreset = "blank" | "sine" | "cosine" | "quadratic" | "line" | "parametric" | "numberLine";

export type GraphTickMode = "number" | "pi";

export type GraphCurveMode = "yOfX" | "xOfY" | "parametric" | "implicit";

export type GraphCurveDash = "solid" | "dashed" | "dotted";

export type GraphFillPattern = "solid" | "diagonal" | "diagonalBack" | "cross" | "horizontal" | "vertical" | "dots";

export interface Graph2DSpec {
    kind: Graph2DKind;
    title: string;
    width: number;
    height: number;
    viewBox: GraphViewBox;
    graphViewBox?: GraphViewBox;
    axes: GraphAxes;
    curves: GraphCurve[];
    parameters?: GraphParameter[];
    points?: GraphPoint[];
    annotations?: GraphAnnotation[];
    fills?: GraphFillRegion[];
    showFormulaLabels?: boolean;
}

export interface GraphViewBox {
    xMin: string;
    xMax: string;
    yMin: string;
    yMax: string;
}

export interface GraphAxes {
    grid: boolean;
    showX?: boolean;
    showY?: boolean;
    showTicks?: boolean;
    axisDash?: GraphCurveDash;
    axisColor?: string;
    axisStrokeWidth?: number;
    xLabel?: string;
    yLabel?: string;
    originLabel?: string;
    /** Tick label font size in points. */
    tickFontSize?: number;
    xTickStep?: string;
    yTickStep?: string;
    xTickMode?: GraphTickMode;
    yTickMode?: GraphTickMode;
}

export interface GraphCurve {
    id: string;
    /** `yOfX`: y=f(x), `xOfY`: x=f(y), `parametric`: x=f(t), `implicit`: F(x,y)=0. 評価用の正規化済み式 (正本)。 */
    expr: string;
    /** Used only when `mode` is `"parametric"`: y=g(t). */
    yExpr?: string;
    /** ユーザーが入力した TeX (表示・再編集用の投影)。無ければ `expr` から導出する。 */
    exprTex?: string;
    /** `yExpr` に対応する入力 TeX。 */
    yExprTex?: string;
    label?: string;
    color: string;
    mode?: GraphCurveMode;
    dash?: GraphCurveDash;
    strokeWidth?: number;
    domain?: {
        min?: string;
        max?: string;
    };
    samples?: number;
}

/** 点ラベルを置く方位 (8方位)。未指定なら曲線・軸・他の点/ラベルを避けて自動配置する。 */
export type GraphPointLabelPlacement = "n" | "ne" | "e" | "se" | "s" | "sw" | "w" | "nw";

export interface GraphPoint {
    id: string;
    x: string;
    y: string;
    /** ユーザーが入力した座標 TeX (表示・再編集用の投影)。無ければ `x`/`y` から導出する。 */
    xTex?: string;
    yTex?: string;
    label?: string;
    /** ラベルを置く方位。省略時は曲線・軸・他要素と重ならない位置を自動選択する。 */
    labelPlacement?: GraphPointLabelPlacement;
    color?: string;
    fill?: "solid" | "none";
    radius?: number;
    showXProjection?: boolean;
    showYProjection?: boolean;
}

export interface GraphAnnotation {
    id: string;
    x: string;
    y: string;
    text: string;
}

export interface GraphFillRegion {
    id: string;
    x: string;
    y: string;
    color?: string;
    opacity?: number;
    pattern?: GraphFillPattern;
}

/**
 * Engine-neutral mathematical 3D model persisted in SigmaDoc.
 *
 * Expressions are deliberately stored as authored strings. Syntax and numeric
 * evaluation errors are editor diagnostics, not persistence errors, so an
 * unfinished expression is never dropped while the user is typing.
 */
export type Graph3DExpression = string;

export type Graph3DPreset = "revolution" | "surface" | "tricylinder" | "sphereTetrahedron" | "blank";

export interface Graph3DExpressionVector3 {
    x: Graph3DExpression;
    y: Graph3DExpression;
    z: Graph3DExpression;
}

export interface Graph3DNumericVector3 {
    x: number;
    y: number;
    z: number;
}

export interface Graph3DExpressionRange {
    min: Graph3DExpression;
    max: Graph3DExpression;
    samples?: number;
}

export interface Graph3DBounds {
    x: Graph3DExpressionRange;
    y: Graph3DExpressionRange;
    z: Graph3DExpressionRange;
}

export type Graph3DParameter = GraphParameter;

export type Graph3DParameterAnimation = GraphParameterAnimation;

export type Graph3DFillStyle = {
    mode: "none";
} | {
    mode: "solid";
    color: string;
    opacity?: number;
} | {
    mode: "pattern";
    color: string;
    opacity?: number;
    pattern: "diagonal" | "cross" | "dots";
};

export interface Graph3DObjectStyle {
    color?: string;
    opacity?: number;
    wireframe?: boolean;
    wireframeColor?: string;
    fill?: Graph3DFillStyle;
}

interface Graph3DObjectBase {
    id: string;
    name?: string;
    visible?: boolean;
    style?: Graph3DObjectStyle;
    /**
     * Local Euler rotation in radians, applied x→y→z around the object's own centre.
     * Every solid can be turned from its on-figure axes; omitted means no extra turn.
     */
    rotation?: Graph3DExpressionVector3;
    /** Translation in world coordinates, applied after local scale and rotation. */
    translation?: Graph3DExpressionVector3;
    /** Positive scale along the object's local x/y/z axes. */
    scale?: Graph3DExpressionVector3;
}

export interface Graph3DImplicitSurfaceObject extends Graph3DObjectBase {
    kind: "implicitSurface";
    /**
     * The surface's equation, for example `x^2 + y^2 + z^2 = 1`.
     * A form without `=` is read as its zero-level set, so `x^2 + y^2 + z^2 - 1` is the same surface.
     */
    expression: Graph3DExpression;
    bounds: Graph3DBounds;
    resolution?: number;
}

export interface Graph3DParametricCurveObject extends Graph3DObjectBase {
    kind: "parametricCurve";
    x: Graph3DExpression;
    y: Graph3DExpression;
    z: Graph3DExpression;
    parameter: string;
    range: Graph3DExpressionRange;
}

export interface Graph3DParametricSurfaceObject extends Graph3DObjectBase {
    kind: "parametricSurface";
    x: Graph3DExpression;
    y: Graph3DExpression;
    z: Graph3DExpression;
    u: Graph3DExpressionRange;
    v: Graph3DExpressionRange;
}

export interface Graph3DPrimitiveObject extends Graph3DObjectBase {
    kind: "primitive";
    primitive: "sphere" | "cylinder" | "cone" | "box";
    center: Graph3DExpressionVector3;
    /** Local x/y/z extents. Primitive presets translate these to engine geometry. */
    size: Graph3DExpressionVector3;
    /**
     * Segments around a curved primitive. Omitted — the normal case — means the count follows the
     * radius, so a sphere stays as smooth when it is made bigger. A box ignores it.
     */
    resolution?: number;
}

/**
 * A custom rotation axis defined as the intersection of two affine planes.
 * For example, `x = y` and `z = 0` intersect in the line `(t, t, 0)`.
 */
export interface Graph3DPlaneIntersectionAxis {
    kind: "planeIntersection";
    equations: [
        Graph3DExpression,
        Graph3DExpression
    ];
    /** Parameter used by the radius expression and the authored axis range. */
    parameter?: string;
}

export type Graph3DRevolutionAxis = "x" | "y" | "z" | Graph3DPlaneIntersectionAxis;

export interface Graph3DSolidOfRevolutionObject extends Graph3DObjectBase {
    kind: "solidOfRevolution";
    axis: Graph3DRevolutionAxis;
    radius: Graph3DExpression;
    axisRange: Graph3DExpressionRange;
    angleRange?: Graph3DExpressionRange;
    capped?: boolean;
}

export interface Graph3DPolyhedronObject extends Graph3DObjectBase {
    kind: "polyhedron";
    vertices: Graph3DExpressionVector3[];
    /** Each face stores zero-based indices into `vertices`. */
    faces: number[][];
}

export interface Graph3DBoundedSolidObject extends Graph3DObjectBase {
    kind: "boundedSolid";
    /** Inequalities such as `x >= 0` and `x + y + z <= 1`. */
    inequalities: Graph3DExpression[];
    bounds: Graph3DBounds;
    resolution?: number;
}

export interface Graph3DPointObject extends Graph3DObjectBase {
    kind: "point";
    position: Graph3DExpressionVector3;
    radius?: number;
}

export interface Graph3DSegmentObject extends Graph3DObjectBase {
    kind: "segment";
    from: Graph3DExpressionVector3;
    to: Graph3DExpressionVector3;
}

export interface Graph3DPlaneObject extends Graph3DObjectBase {
    kind: "plane";
    plane: Graph3DPlaneDefinition;
    size?: Graph3DExpressionVector3;
}

export type Graph3DObject = Graph3DImplicitSurfaceObject | Graph3DParametricCurveObject | Graph3DParametricSurfaceObject | Graph3DPrimitiveObject | Graph3DSolidOfRevolutionObject | Graph3DPolyhedronObject | Graph3DBoundedSolidObject | Graph3DPointObject | Graph3DSegmentObject | Graph3DPlaneObject;

export type Graph3DPlaneDefinition = {
    kind: "equation";
    /** Affine equation such as `x + y = 1` or `z = s`. */
    expression: Graph3DExpression;
} | {
    kind: "threePoints";
    points: [
        Graph3DExpressionVector3,
        Graph3DExpressionVector3,
        Graph3DExpressionVector3
    ];
} | {
    kind: "pointNormal";
    point: Graph3DExpressionVector3;
    normal: Graph3DExpressionVector3;
};

export type Graph3DSectionOverlapMode = "add" | "subtract";

export interface Graph3DSectionDisplay {
    showInScene?: boolean;
    showFlattened2D?: boolean;
    fill?: Graph3DFillStyle;
    lineColor?: string;
    lineWidth?: number;
    /** How later target-object sections combine with the first section in flattened views. */
    overlapMode?: Graph3DSectionOverlapMode;
}

export interface Graph3DSectionTrail {
    parameterId: string;
    samples: number;
    color?: string;
    opacity?: number;
}

export interface Graph3DCut {
    id: string;
    label?: string;
    /** An empty list means all visible objects. */
    targetObjectIds: string[];
    plane: Graph3DPlaneDefinition;
    visible?: boolean;
    showPlane?: boolean;
    showContour?: boolean;
    section?: Graph3DSectionDisplay;
    trail?: Graph3DSectionTrail;
}

/**
 * The part two or more objects have in common, drawn in its own colour.
 *
 * This is not a cut: nothing is sliced away. The shared part is whatever dimension the members
 * leave — a volume between solids, a flat area once one member is a plane, a piece of a shell that
 * has no inside of its own, a line where two planes meet, a single point where three do. An empty
 * common part is a legitimate answer and simply draws nothing.
 */
export interface Graph3DObjectIntersectionRegion {
    id: string;
    kind: "objectIntersection";
    label?: string;
    /** Two or more object ids. Fewer than two has nothing in common to draw. */
    objectIds: string[];
    fill: Graph3DFillStyle;
    visible?: boolean;
    /** Grid density used when the shared volume has to be sampled. */
    resolution?: number;
    showEdges?: boolean;
    edgeColor?: string;
}

export type Graph3DRegion = {
    id: string;
    kind: "section";
    cutId: string;
    fill: Graph3DFillStyle;
} | {
    id: string;
    kind: "inequality";
    inequalities: Graph3DExpression[];
    bounds: Graph3DBounds;
    fill: Graph3DFillStyle;
} | Graph3DObjectIntersectionRegion;

/** Stroke pattern shared by dimension lines. */
export type Graph3DLineStyle = "solid" | "dashed" | "dotted";

/**
 * Ends of a dimension line. Same table as coordinate axes, so the picker and the drawing
 * share one set of heads. `"tick"` is the older name for `"bar"` and is still read from saved documents.
 */
export type Graph3DDimensionEndStyle = Graph3DAxisEndStyle | "tick";

export declare function resolveGraph3DDimensionEndStyle(endStyle: Graph3DDimensionEndStyle | undefined): Graph3DAxisEndStyle;

export type Graph3DAnnotation = {
    id: string;
    kind: "label";
    position: Graph3DExpressionVector3;
    labelTex: string;
    color?: string;
} | {
    id: string;
    kind: "dimension";
    from: Graph3DExpressionVector3;
    to: Graph3DExpressionVector3;
    labelTex: string;
    color?: string;
    /** Omitted means `solid`. */
    lineStyle?: Graph3DLineStyle;
    /** Drawn thickness on the same scale as a section contour. Omitted means 1.5. */
    lineWidth?: number;
    /** Omitted means `arrow`. */
    endStyle?: Graph3DDimensionEndStyle;
};

export interface Graph3DCamera {
    projection: "perspective" | "orthographic";
    position: Graph3DNumericVector3;
    target: Graph3DNumericVector3;
    up: Graph3DNumericVector3;
    fov?: number;
    zoom?: number;
}

/** Per-axis drawing colour. Axis labels take the same colour as their axis. */
export interface Graph3DAxisColors {
    x: string;
    y: string;
    z: string;
}

/** Stroke pattern used by all three coordinate axes. */
export type Graph3DAxisLineStyle = "solid" | "dashed" | "dotted";

/**
 * Positive-end decoration used by all three coordinate axes.
 *
 * The names are the overlay endpoint heads: an axis end and a line end are drawn from one table of
 * outlines (`ARROWHEAD_MARKER_SPECS`), so the two lists have to hold the same names.
 */
export declare const GRAPH3D_AXIS_END_STYLES: readonly [
    "none",
    "arrow",
    "triangle",
    "openArrow",
    "thinArrow",
    "diamond",
    "dot",
    "bar",
    "arrowSmall",
    "triangleSmall",
    "openArrowSmall",
    "thinArrowSmall",
    "diamondSmall",
    "dotSmall",
    "barSmall"
];

export type Graph3DAxisEndStyle = (typeof GRAPH3D_AXIS_END_STYLES)[number];

export interface Graph3DViewSettings {
    /** Mathematical coordinates are canonical and z-up; renderers adapt as needed. */
    coordinateSystem: "zUp";
    showAxes: boolean;
    showGrid: boolean;
    backgroundColor: string;
    showAxisLabels?: boolean;
    /** Omitted means `DEFAULT_GRAPH3D_AXIS_COLORS`. */
    axisColors?: Graph3DAxisColors;
    /** Omitted means `solid`. */
    axisLineStyle?: Graph3DAxisLineStyle;
    /** Omitted means `arrow`. */
    axisEndStyle?: Graph3DAxisEndStyle;
    shadows?: boolean;
}

/** Textbook convention: x warm, y green, z blue. */
export declare const DEFAULT_GRAPH3D_AXIS_COLORS: Graph3DAxisColors;

export declare function getGraph3DAxisColors(view: Graph3DViewSettings): Graph3DAxisColors;

export interface Graph3DSpec {
    version: 1;
    parameters: Graph3DParameter[];
    objects: Graph3DObject[];
    cuts: Graph3DCut[];
    regions: Graph3DRegion[];
    annotations: Graph3DAnnotation[];
    camera: Graph3DCamera;
    view: Graph3DViewSettings;
}

/** Controls whether inline fractions keep TeX sizing or use display-style fractions. */
export type MathFractionSizing = "uniform" | "texDefault";

export type HeadingNumberingStyle = "decimal" | "sectionSign" | "chapterJa";

export interface HeadingNumberingConfig {
    enabled: boolean;
    style?: HeadingNumberingStyle;
    depth?: 1 | 2 | 3;
}

export interface SigmaMetadata {
    title: string;
    source?: SigmaDocumentSourceMetadata;
    styleUnits?: SigmaDocumentStyleUnits;
    mathFractionSizing?: MathFractionSizing;
    /** Display-only hierarchical numbering derived from document-order headings. */
    headingNumbering?: HeadingNumberingConfig;
    /** File-scoped TeX macro declarations used by MathLive, KaTeX, and print output. */
    texPreamble?: string;
}

export interface SigmaDocumentSourceMetadata {
    /** Descriptive provenance supplied by an external authoring tool. */
    format?: string;
    layoutMode?: "fixedOverlay";
    printFlowContent?: boolean;
    /** Import provenance. Descriptive only - never an input to layout or rendering. */
    originalFileName?: string;
    importedAt?: string;
    slideCount?: number;
    pageSize?: {
        widthPx?: number;
        heightPx?: number;
        widthMm?: number;
        heightMm?: number;
    };
}

export interface SigmaDocumentStyleUnits {
    fontSize?: "pt";
}

export type PageSizePreset = "A4" | "A3" | "B5" | "B4" | "custom" | "whiteboard";

export type PageOrientation = "portrait" | "landscape";

/**
 * 紙／無限キャンバスの下地。ホワイトボードの既定は `"dots"`。
 *
 * 型名を `WhiteboardBackground` にしていないのは、印刷の切り出し
 * (`cropWhiteboardDocumentForPrint`) がホワイトボードを `preset: "custom"` の 1 枚紙へ
 * 投影するため。**用紙プリセットでも保持されなければならないフィールド**であって、
 * ホワイトボード専用ではない。
 */
export type PageBackground = "grid" | "dots" | "none";

/**
 * 下地 1 マスのワールド座標での大きさ。
 *
 * 描画側 (キャンバスのパターン生成) と印刷側 (切り出し原点のセル合わせ) の**両方**が
 * 同じ値を見る必要があるのでモデル層に置く。片方だけ変えると、紙面のマス目が画面の
 * ワールドグリッドと位相ずれする。
 */
export declare const WHITEBOARD_BASE_CELL_PX = 24;

export interface PageLayout {
    preset: PageSizePreset;
    orientation: PageOrientation;
    pageSize: {
        widthMm: number;
        heightMm: number;
    };
    marginsMm: {
        top: number;
        right: number;
        bottom: number;
        left: number;
    };
    flow: {
        type: "columns";
        columnCount: number;
        columnGapMm: number;
        columnRule?: ColumnRule;
    };
    header?: PageRunningRegion;
    footer?: PageRunningRegion;
    /** Single continuous overlay for the whole document (figures resolve their page from block anchors). */
    overlay?: PageOverlay;
    /** 下地のパターン。用紙プリセットでは通常 `undefined` (無地)。 */
    background?: PageBackground;
}

export interface PageRunningRegion {
    enabled: boolean;
    heightMm: number;
    offsetMm: number;
    showOnFirstPage: boolean;
    /** Free-form header/footer body. This is the canonical repeated text content. */
    blocks: RichBlock[];
    /** Repeated overlay for figures, images, graphs, and free-positioned text inside this region. */
    overlay?: PageOverlay;
}

/**
 * `overlaySnapshot` is the only source for overlay figures. Previews, exports, and
 * print output are always regenerated from it — no serialized SVG is ever persisted.
 */
export interface PageOverlay {
    overlaySnapshot?: OverlaySnapshot;
    updatedAt?: string;
}

export type TextAlign = "left" | "center" | "right" | "justify";

/** Unitless CSS line-height multiplier, normalized by `normalizeLineHeight`. */
export type LineHeight = string;

export type InlineNode = TextInlineNode | MathInlineNode;

export interface TextInlineNode {
    type: "text";
    text: string;
    marks?: TextMark[];
    color?: string;
    backgroundColor?: string;
    fontFamily?: string;
    fontSize?: number;
    boxedPaddingY?: number;
    boxedVariant?: BoxedVariant;
    boxedTone?: BoxedTone;
}

export type TextMark = "bold" | "italic" | "underline" | "boxed";

/**
 * Visual style of a boxed run, modeled after common TeX box commands:
 * `frame` (\fbox), `thick`, `double`, `oval` (\ovalbox), and `shade` (\tcolorbox / \itembox).
 * Absent means `frame`, so existing boxed runs keep their thin-border look.
 */
export type BoxedVariant = "frame" | "thick" | "double" | "oval" | "shade";

/** Fill colour preset for `shade` boxes. Absent means `gray`. */
export type BoxedTone = "gray" | "blue" | "green" | "red" | "yellow";

export interface MathInlineNode {
    type: "mathInline";
    id: string;
    tex: string;
    display: "inline";
    marks?: Array<Extract<TextMark, "underline" | "boxed">>;
    color?: string;
    backgroundColor?: string;
    fontFamily?: string;
    fontSize?: number;
    boxedPaddingY?: number;
    boxedVariant?: BoxedVariant;
    boxedTone?: BoxedTone;
    semanticRole?: "expression" | "equation" | "variable";
    altText?: string;
}

/** Plain-text projection used by search, labels, and editor-only summaries. */
export declare function inlineNodesToPlainText(children: readonly InlineNode[]): string;

/**
 * The Excel error values this engine can produce.
 *
 * They are the canonical ASCII spellings on purpose: this is the document layer, so the value a
 * formula cell holds must not depend on the viewer's language. Localized wording belongs in a
 * tooltip drawn by the UI, never in what the cell displays.
 */
export type SigmaTableFormulaErrorCode = "#DIV/0!" | "#NAME?" | "#REF!" | "#VALUE!" | "#NUM!" | "#N/A" | "#CYCLE!";

/** What one cell holds, once formulas are resolved. */
export type SigmaTableCellValue = {
    kind: "number";
    value: number;
} | {
    kind: "text";
    text: string;
} | {
    kind: "empty";
} | {
    kind: "error";
    code: SigmaTableFormulaErrorCode;
};

export interface SigmaTableFormulaResult {
    /** The source as written, `=` included. */
    source: string;
    value: SigmaTableCellValue;
    /** Locale-independent display text: the number, the text, or the error code. */
    display: string;
    error: SigmaTableFormulaErrorCode | null;
}

export interface SigmaTableEvaluation {
    /**
     * Keyed by `SigmaTableCell.id`, holding only the cells that carry a formula this engine could
     * parse. A cell whose source cannot be parsed is absent on purpose — the surfaces then draw the
     * source text as written, which is how an in-progress `=SUM(A1` keeps looking like what was typed
     * instead of turning into an error value.
     */
    byCellId: ReadonlyMap<string, SigmaTableFormulaResult>;
    /**
     * The same results, keyed by the cell object itself. **Prefer this for anything that draws** —
     * `byCellId` cannot tell two cells apart when a document gives them the same id.
     *
     * This is what the drawing surfaces read. Nothing validates that `cells[].id` is unique — the
     * schema checks row and column ids but not cell ids — so a document giving an ordinary cell the
     * same id as a formula cell would make the ordinary one *display the formula's value* on the
     * canvas, in print and in the exported SVG, while its stored text stayed untouched. Identity
     * cannot be forged by a document.
     */
    byCell: WeakMap<SigmaTableCell, SigmaTableFormulaResult>;
}

/**
 * The formula a cell carries, or `null` when it carries something else.
 *
 * A formula cell is one paragraph of plain text starting with `=`. A cell holding an inline math
 * node, a trend arrow, or a second paragraph is deliberately *not* a formula: those carry structure
 * that flattening to a source string would silently discard.
 */
export declare function getTableCellFormulaSource(cell: SigmaTableCell | undefined): string | null;

/**
 * Every formula in one table, evaluated.
 *
 * Memoized on the identity of the table, which is both the arithmetic saved and the point: the SVG
 * export memoizes table markup on the identity of what it is handed, so returning a fresh map per
 * call would make that cache miss on every render — the same reason `resolveChartData` memoizes.
 * The overlay model treats a `SigmaTableSpec` as an immutable snapshot, so identity is a sound key
 * with no invalidation logic, and the map is held weakly so nothing needs evicting.
 *
 * References resolve inside this table only. That is not a simplification of the feature but a
 * consequence of the render port: `renderTableHtml` is handed one table and no neighbours, so a
 * cross-table reference could not be resolved on the static path at all.
 */
export declare function evaluateTableFormulas(table: SigmaTableSpec): SigmaTableEvaluation;

/**
 * The colour an error value is drawn in — `--danger` in `globals.css`, as a literal.
 *
 * It travels on the projected run rather than in a stylesheet because the same nodes are drawn into
 * the self-contained SVG export, which is viewed with no stylesheet at all.
 */
export declare const TABLE_FORMULA_ERROR_COLOR = "#b42318";

/**
 * The evaluation of the formula this paragraph holds, or `null` when it holds something else.
 *
 * `null` covers three cases that all mean the same thing to a caller — the cell is not a formula,
 * the formula could not be parsed, or this paragraph is not the one the formula was typed into —
 * and in every one of them the cell should be drawn exactly as it is stored.
 */
export declare function getTableCellFormulaResult(table: SigmaTableSpec, cell: SigmaTableCell | undefined, content: SigmaTableCellParagraph): SigmaTableFormulaResult | null;

/**
 * What a cell's paragraph should draw: the evaluated value for a formula, its own nodes otherwise.
 *
 * Every surface that draws a table cell ends at an `InlineNode[]`, so projecting the value back
 * into that shape is what lets the editing canvas, the static tree, the print path, the SVG export
 * and the settings preview all show the same thing by changing one argument each — and it adds no
 * DOM, which the editing/display parity tests compare geometrically.
 */
export declare function getTableCellDisplayNodes(table: SigmaTableSpec, cell: SigmaTableCell | undefined, content: SigmaTableCellParagraph): readonly InlineNode[];

/**
 * One cell as it sits on the grid: the position it starts at and how far it reaches.
 *
 * `cell` is absent where the table declares no cell for that position; the placement still exists so
 * every grid position has an occupant and callers never index into a hole.
 */
export interface SigmaTableCellPlacement {
    cell: SigmaTableCell | undefined;
    rowIndex: number;
    columnIndex: number;
    rowSpan: number;
    colSpan: number;
}

export interface SigmaTableCellMatrix {
    rowCount: number;
    columnCount: number;
    /** Placements that *start* in each row, in column order. Covered positions are omitted. */
    origins: SigmaTableCellPlacement[][];
    /** The placement occupying each grid position, indexed `[rowIndex][columnIndex]`. */
    occupants: SigmaTableCellPlacement[][];
}

/**
 * Expands `rowSpan`/`colSpan` once, for every reader that needs to know which cell owns a position.
 *
 * The layout model (`overlay-table-read-model.ts`) walks `origins` to place DOM cells; the chart
 * derivation walks `occupants` so a merged header names every column it visually covers. Keeping a
 * single expansion is what makes those two agree.
 */
export declare function getTableCellMatrix(table: SigmaTableSpec): SigmaTableCellMatrix;

/**
 * Parses one cell's text as a number.
 *
 * NFKC folds the full-width digits and punctuation a Japanese keyboard produces; a bare `$…$` (how
 * inline math serializes) is unwrapped so a number typed as a formula still counts. Anything else —
 * an em dash, prose, a hex literal — is `null`.
 *
 * Separators are removed narrowly, on purpose. Stripping every space and comma would read the two
 * tokens `1 2` as `12` and the European decimal `1,2` as `12` — a *wrong* plotted value, which is
 * far worse than the gap an unparseable cell leaves. So internal whitespace disqualifies the cell
 * outright, and commas are dropped only where they group digits in threes.
 *
 * It lives beside the grid expansion rather than with the chart derivation because the formula
 * engine reads cells through it too: one table, one answer to "is this cell a number".
 */
export declare function parseChartNumber(text: string): number | null;

export type OverlayShapeId = string;

export type OverlayAssetId = string;

export type OverlayGroupId = string;

export type OverlayGraphAxisLabelKey = "x" | "y" | "origin";

export type OverlayStackLayer = "foreground" | "background";

export type OverlayExtensionValue = null | boolean | number | string | readonly unknown[] | {
    readonly [key: string]: unknown;
};

export type OverlayExtensions = Record<string, OverlayExtensionValue>;

export type OverlayTextSize = "s" | "m" | "l" | "xl";

export type OverlayRegularPolygonSides = 5 | 6 | 7 | 8 | 9 | 10 | 11 | 12;

export type OverlayDash = "solid" | "dashed" | "dotted";

/**
 * Every line/arc endpoint decoration, in the order the toolbar offers them.
 *
 * This array is the single definition of the set: the type, the validator, the MCP schema and the
 * marker specs are all derived from it, so a new head cannot reach one of them and miss another.
 * Existing values keep their name and their meaning — documents store these strings verbatim.
 */
export declare const OVERLAY_ARROWHEADS: readonly [
    "none",
    "arrow",
    "triangle",
    "openArrow",
    "thinArrow",
    "diamond",
    "dot",
    "bar",
    "arrowSmall",
    "triangleSmall",
    "openArrowSmall",
    "thinArrowSmall",
    "diamondSmall",
    "dotSmall",
    "barSmall"
];

export type OverlayArrowhead = (typeof OVERLAY_ARROWHEADS)[number];

export type OverlayLineKind = "polyline" | "curve" | "freehand";

/**
 * Content of an overlay text shape: the same blocks the body is made of.
 *
 * Text shapes used to carry their own paragraph/heading pair (`OverlayRichTextDocument`), so the
 * viewer package had to hand-mirror a second block model that could drift from the body's.
 * `RichBlock` — the body's "blocks that hold prose and no pagination of their own" type, already
 * used by headers/footers — has exactly the properties a shape needs, and reusing it is what lets
 * a shape hold a list.
 *
 * Quote, code and divider are added on top of it rather than added *to* it. `RichBlock` leaves
 * `divider` out on purpose because headers and footers are built from it, and a block with no
 * children in a region that is duplicated and measured per page makes every `children`-assuming
 * path there grow a branch (see its note in `model/blocks.ts`). A shape is not that region: it is
 * one box, measured once, so the three blocks cost it nothing — and widening `RichBlock` to reach
 * them would change what a header accepts, which nobody asked for.
 *
 * What is deliberately still out: `boxBlock`, `layoutSection`, `problem` and `section`. Those are
 * page-level furniture — a box that paginates, a column band, a numbered problem — and a shape is
 * a box drawn on top of the page, not a place that owns page structure.
 */
export type OverlayTextBlock = RichBlock | QuoteBlockNode | CodeBlockNode | DividerNode;

export interface OverlaySnapshot {
    version: 1;
    shapes: OverlayShape[];
    assets: Record<OverlayAssetId, OverlayAsset>;
    /**
     * Namespaced, JSON-only extension data. Canonical shape and asset objects do
     * not accept arbitrary metadata fields.
     */
    extensions?: OverlayExtensions;
}

export interface OverlayStorageAssetRef {
    kind: "remote-asset";
    storageKey: string;
    assetId: string;
}

export interface OverlayAsset {
    id: OverlayAssetId;
    type: "image";
    props: {
        w: number;
        h: number;
        name: string;
        isAnimated: boolean;
        mimeType: string | null;
        src: string;
        fileSize: number;
        storage?: OverlayStorageAssetRef;
    };
}

export type OverlayShape = OverlayGroupShape | OverlayGeoShape | OverlayArcShape | OverlayArrowShape | OverlayLineShape | OverlayTextShape | OverlayImageShape | OverlayCalloutShape | OverlayGraphShape | OverlayGraph3DShape | OverlayTableShape | OverlayChartShape;

export type OverlayAnchor = {
    type: "block";
    blockId: string;
    dy: number;
    dx?: number;
    line?: OverlayLineAnchor;
    reserveSpace?: boolean;
} | {
    type: "shape";
    shapeId: OverlayShapeId;
    dx: number;
    dy: number;
    rx?: number;
    ry?: number;
} | {
    type: "page";
};

export interface OverlayLineAnchor {
    index: number;
    dy: number;
}

export type OverlayShapePatch = {
    id: OverlayShapeId;
    type: OverlayShape["type"];
    x?: number;
    y?: number;
    rotation?: number;
    flipX?: boolean;
    flipY?: boolean;
    parentId?: OverlayShapeId;
    groupId?: OverlayGroupId;
    stackLayer?: OverlayStackLayer;
    locked?: boolean;
    hidden?: boolean;
    opacity?: number;
    anchor?: OverlayAnchor;
    props?: Record<string, unknown>;
};

interface OverlayBaseShape<Type extends string, Props> {
    id: OverlayShapeId;
    type: Type;
    x: number;
    y: number;
    rotation?: number;
    /** Mirrors the rendered shape in its local horizontal axis. Absent means false. */
    flipX?: boolean;
    /** Mirrors the rendered shape in its local vertical axis. Absent means false. */
    flipY?: boolean;
    parentId?: OverlayShapeId;
    /** Input-only grouping marker. Normalized snapshots use explicit group shapes and parentId. */
    groupId?: OverlayGroupId;
    stackLayer?: OverlayStackLayer;
    locked?: boolean;
    hidden?: boolean;
    opacity?: number;
    /** Vertical anchor. Absent ≡ { type: "page" } (y is used as the page-absolute value). */
    anchor?: OverlayAnchor;
    props: Props;
}

export type OverlayGroupShape = OverlayBaseShape<"group", {
    w: number;
    h: number;
    name?: string;
}>;

export type OverlayGeoShape = OverlayBaseShape<"geo", {
    w: number;
    h: number;
    geo: "rectangle" | "ellipse" | "triangle" | "diamond" | "pentagon" | "regularPolygon" | "blockArrow";
    polygonSides?: OverlayRegularPolygonSides;
    apexX?: number;
    headLengthRatio?: number;
    shaftRatio?: number;
    /** 角丸半径(px)。rectangle のみ有効。未指定は角あり。 */
    radius?: number;
    fill: "none" | "solid";
    color: string;
    fillColor?: string;
    strokeOpacity?: number;
    fillOpacity?: number;
    labelColor: string;
    dash: OverlayDash;
    size: OverlayTextSize;
    label?: string;
}>;

export type OverlayArcShape = OverlayBaseShape<"arc", {
    kind?: "arc" | "sector";
    r: number;
    rx?: number;
    ry?: number;
    startAngle: number;
    endAngle: number;
    arrowheadStart?: OverlayArrowhead;
    arrowheadEnd?: OverlayArrowhead;
    fill?: "none" | "solid";
    fillColor?: string;
    fillOpacity?: number;
    color: string;
    strokeOpacity?: number;
    dash: OverlayDash;
    size: OverlayTextSize;
}>;

export type OverlayArrowShape = OverlayBaseShape<"arrow", {
    start: OverlayPoint;
    end: OverlayPoint;
    arrowheadStart?: OverlayArrowhead;
    arrowheadEnd: OverlayArrowhead;
    fill: "none";
    color: string;
    strokeOpacity?: number;
    labelColor: string;
    dash: OverlayDash;
    size: OverlayTextSize;
    label?: string;
}>;

export type OverlayLineShape = OverlayBaseShape<"line", {
    kind?: OverlayLineKind;
    points: OverlayPoint[];
    closed: boolean;
    arrowheadStart?: OverlayArrowhead;
    arrowheadEnd?: OverlayArrowhead;
    fill?: "none" | "solid";
    fillColor?: string;
    fillOpacity?: number;
    fillPattern?: "diagonalHatch";
    color: string;
    strokeOpacity?: number;
    labelColor?: string;
    dash: OverlayDash;
    size: OverlayTextSize;
    label?: string;
}>;

export type OverlayTextShape = OverlayBaseShape<"text", {
    /** User-chosen width. Text wraps at this width; changing it never changes the font size. */
    w: number;
    /** Derived height cache written back from the measured DOM. Never edited directly. */
    h: number;
    blocks: OverlayTextBlock[];
    color: string;
    /** Font size in points. Shape bounds and positions remain CSS pixels. */
    fontSize?: number;
    size: OverlayTextSize;
}>;

export type OverlayImageShape = OverlayBaseShape<"image", {
    assetId: OverlayAssetId;
    w: number;
    h: number;
    crop?: OverlayImageCrop;
}>;

export interface OverlayImageCrop {
    topLeft: OverlayPoint;
    bottomRight: OverlayPoint;
}

export type OverlayCalloutShape = OverlayBaseShape<"callout", {
    /** 吹き出し本文の矩形サイズ。口はこの矩形の外側へはみ出せる。 */
    w: number;
    h: number;
    /** 本文矩形の角丸半径(px)。 */
    radius: number;
    /** 口の麓2点と頂点。麓はそれぞれ独立して本文矩形の外周を移動する。 */
    tail: {
        baseStart: OverlayPoint;
        baseEnd: OverlayPoint;
        tip: OverlayPoint;
    };
    /** 本文・図中数式と同じ永続化用ブロック列。 */
    blocks: OverlayTextBlock[];
    color: string;
    /** Font size in points. Shape bounds and positions remain CSS pixels. */
    fontSize?: number;
    size: OverlayTextSize;
    /** 枠線の種類(実線・破線・点線)。 */
    dash: OverlayDash;
    /** 枠線の太さプリセット。テキストサイズの `size` とは独立。 */
    strokeWidth: OverlayTextSize;
}>;

export type OverlayRichTextShape = OverlayTextShape | OverlayCalloutShape;

export type OverlayGraphShape = OverlayBaseShape<"graph2dShape", {
    /** `x`/`y`/`w`/`h` describe the visible plot rectangle; SVG label margins are render-only. */
    boundsMode?: "plot";
    w: number;
    h: number;
    spec: Graph2DSpec;
    preserveSpecSize?: boolean;
    axisLabelTextShapeIds?: Partial<Record<OverlayGraphAxisLabelKey, OverlayShapeId>>;
    pointLabelTextShapeIdsByPointId?: Record<string, OverlayShapeId>;
    annotationTextShapeIdsByAnnotationId?: Record<string, OverlayShapeId>;
    labelTextShapeIds?: OverlayShapeId[];
    labelTextShapeIdsByCurveId?: Record<string, OverlayShapeId>;
}>;

export type OverlayGraph3DShape = OverlayBaseShape<"graph3dShape", {
    w: number;
    h: number;
    spec: Graph3DSpec;
    /** Derived image used by the page, print, and viewer renderers. */
    previewAssetId?: OverlayAssetId;
    /** Hash of the spec/camera state used to detect a stale derived preview. */
    previewSourceHash?: string;
}>;

export type OverlayTableShape = OverlayBaseShape<"tableShape", {
    w: number;
    h: number;
    table: SigmaTableSpec;
}>;

export type OverlayChartShape = OverlayBaseShape<"chartShape", {
    w: number;
    h: number;
    spec: SigmaChartSpec;
    /**
     * The table shape this chart reads. Renderers resolve it against the whole snapshot every draw,
     * which is what makes editing the table move the chart.
     */
    sourceTableShapeId?: OverlayShapeId;
    /**
     * The last data derived from that table, drawn when the reference no longer resolves (the table
     * was deleted, the chart was pasted alone, or it lives in a running region the body cannot reach).
     */
    dataSnapshot: SigmaChartData;
}>;

export type SigmaTableKind = "plain" | "variation";

export type SigmaTableColumnRole = "label" | "point" | "interval" | "value";

export type SigmaTableRowRole = "header" | "body" | "variable" | "derivative" | "variation" | "note";

export type SigmaTableVerticalAlign = "top" | "middle" | "bottom";

export type SigmaTableTrendDirection = "up" | "down" | "flat";

export type SigmaTableBorderStyle = "solid" | "dashed" | "dotted" | "double";

export type SigmaTableGridLineAxis = "vertical" | "horizontal";

export interface SigmaTableGridLineStyle {
    visible?: boolean;
    borderColor?: string;
    borderWidth?: number;
    borderStyle?: SigmaTableBorderStyle;
}

export type SigmaTableGridLineOverride = {
    axis: "vertical";
    edge: "left" | "right";
    style: SigmaTableGridLineStyle;
} | {
    axis: "vertical";
    beforeColumnId: string;
    style: SigmaTableGridLineStyle;
} | {
    axis: "horizontal";
    edge: "top" | "bottom";
    style: SigmaTableGridLineStyle;
} | {
    axis: "horizontal";
    beforeRowId: string;
    style: SigmaTableGridLineStyle;
};

export type SigmaTableTrackSize = {
    mode: "auto";
    min?: number;
    max?: number;
} | {
    mode: "fixed";
    value: number;
} | {
    mode: "fr";
    value: number;
    min?: number;
    max?: number;
};

export interface SigmaTableSpec {
    version: 1;
    kind: SigmaTableKind;
    columns: SigmaTableColumn[];
    rows: SigmaTableRow[];
    cells: SigmaTableCell[];
    grid: SigmaTableGridStyle;
    defaultCellStyle: SigmaTableCellStyle;
}

export interface SigmaTableColumn {
    id: string;
    width: SigmaTableTrackSize;
    role?: SigmaTableColumnRole;
}

export interface SigmaTableRow {
    id: string;
    height: SigmaTableTrackSize;
    role?: SigmaTableRowRole;
}

export interface SigmaTableCell {
    id: string;
    rowId: string;
    columnId: string;
    rowSpan?: number;
    colSpan?: number;
    content: SigmaTableCellContent[];
    style?: Partial<SigmaTableCellStyle>;
}

export type SigmaTableCellContent = SigmaTableCellParagraph | SigmaTableTrend;

export interface SigmaTableCellParagraph {
    type: "paragraph";
    id: string;
    children: InlineNode[];
    align?: TextAlign;
}

export interface SigmaTableTrend {
    type: "trend";
    id: string;
    direction: SigmaTableTrendDirection;
    label?: InlineNode[];
}

export interface SigmaTableGridStyle {
    borderColor: string;
    borderWidth: number;
    borderStyle?: SigmaTableBorderStyle;
    showOuterBorder?: boolean;
    showInnerBorders?: boolean;
    lineOverrides?: SigmaTableGridLineOverride[];
}

export interface SigmaTableCellStyle {
    align?: TextAlign;
    verticalAlign?: SigmaTableVerticalAlign;
    paddingX?: number;
    paddingY?: number;
    color?: string;
    backgroundColor?: string;
    fontFamily?: string;
    fontSize?: number;
    fontWeight?: "normal" | "bold";
}

export interface OverlayPoint {
    x: number;
    y: number;
}

export interface OverlayBounds {
    x: number;
    y: number;
    w: number;
    h: number;
}
