import { describe, expectTypeOf, it } from "vitest";

import type * as Canonical from "..";
import type * as Legacy from "@/types/sigma-doc";

type LegacyAssemblyContract = readonly [
  Legacy.SigmaDocVersion,
  Legacy.OutputProfileName,
  Legacy.SigmaDocument,
  Legacy.OutputProfile,
  Legacy.PageSizePreset,
  Legacy.PageOrientation,
  Legacy.PageLayout,
  Legacy.PageRunningRegion,
  Legacy.PageOverlay,
  Legacy.SigmaMetadata,
  Legacy.SigmaDocumentSourceMetadata,
  Legacy.SigmaDocumentStyleUnits,
  Legacy.SigmaBlock,
  Legacy.RichBlock,
  Legacy.ProblemAreaBlock,
  Legacy.LayoutSectionChildBlock,
  Legacy.BoxBlockChildBlock,
  Legacy.BaseNode,
  Legacy.PaginationHints,
  Legacy.SectionNode,
  Legacy.HeadingNode,
  Legacy.ParagraphNode,
  Legacy.ListNode,
  Legacy.ListItemNode,
  Legacy.ProblemNode,
  Legacy.ProblemAreaKind,
  Legacy.ProblemAreaColumnSpan,
  Legacy.ProblemAreaLayout,
  Legacy.ProblemNumbering,
  Legacy.ProblemFrame,
  Legacy.LayoutSectionNode,
  Legacy.LayoutSectionLayout,
  Legacy.BoxBlockNode,
  Legacy.BoxFrameSpec,
  Legacy.BoxSpacingPx,
  Legacy.BoxDecorationSpec,
  Legacy.AnswerDefinition,
];

type CanonicalAssemblyContract = readonly [
  Canonical.SigmaDocVersion,
  Canonical.OutputProfileName,
  Canonical.SigmaDocument,
  Canonical.OutputProfile,
  Canonical.PageSizePreset,
  Canonical.PageOrientation,
  Canonical.PageLayout,
  Canonical.PageRunningRegion,
  Canonical.PageOverlay,
  Canonical.SigmaMetadata,
  Canonical.SigmaDocumentSourceMetadata,
  Canonical.SigmaDocumentStyleUnits,
  Canonical.SigmaBlock,
  Canonical.RichBlock,
  Canonical.ProblemAreaBlock,
  Canonical.LayoutSectionChildBlock,
  Canonical.BoxBlockChildBlock,
  Canonical.BaseNode,
  Canonical.PaginationHints,
  Canonical.SectionNode,
  Canonical.HeadingNode,
  Canonical.ParagraphNode,
  Canonical.ListNode,
  Canonical.ListItemNode,
  Canonical.ProblemNode,
  Canonical.ProblemAreaKind,
  Canonical.ProblemAreaColumnSpan,
  Canonical.ProblemAreaLayout,
  Canonical.ProblemNumbering,
  Canonical.ProblemFrame,
  Canonical.LayoutSectionNode,
  Canonical.LayoutSectionLayout,
  Canonical.BoxBlockNode,
  Canonical.BoxFrameSpec,
  Canonical.BoxSpacingPx,
  Canonical.BoxDecorationSpec,
  Canonical.AnswerDefinition,
];

describe("SigmaDoc assembly compatibility", () => {
  it("keeps every legacy assembly type identical to the public document model", () => {
    expectTypeOf<LegacyAssemblyContract>().toEqualTypeOf<CanonicalAssemblyContract>();
  });
});
